=== grizzie17/GS8/Config/gauges/Gauges.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="SimBase.Document">
		<xs:complexType>
			<xs:all>
				<xs:element minOccurs="1" maxOccurs="1" name="SimGauge.Gauge">
					<xs:complexType>
						<xs:group ref="GaugeContent_" />
						<xs:attribute name="id" type="xs:string" use="optional" />
						<xs:attribute name="Name" type="xs:string" />
						<xs:attribute name="Crop" type="xs:boolean" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" name="Descr" type="xs:string" />
			</xs:all>
			<xs:attribute name="Type" type="xs:string" use="optional" />
			<xs:attribute name="version" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="Gauge">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="GaugeContent_" />
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" />
			<xs:attribute name="Version" type="xs:float" />
			<xs:attribute name="Crop" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="Float2">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="Equation">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="AttributeEquation">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:attributeGroup name="AttributeStyle_">
		<xs:attribute name="Color" type="AttributeEquation" />
		<xs:attribute name="LineColor" type="AttributeEquation" />
		<xs:attribute name="FillColor" type="AttributeEquation" />
		<xs:attribute name="LineWidth" type="AttributeEquation" />
		<xs:attribute name="HaloColor" type="AttributeEquation" />
	</xs:attributeGroup>
	<xs:attributeGroup name="AttributeXY_">
		<xs:attribute name="X" type="AttributeEquation" />
		<xs:attribute name="Y" type="AttributeEquation" />
	</xs:attributeGroup>
	<xs:group name="GaugeContent_">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group minOccurs="0" maxOccurs="1" ref="Position_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Size_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Element_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Update_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="MouseArea_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="KeyMap_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Comment_" />
				<!--xs:group minOccurs="0" maxOccurs="1" ref="Visibility_" /-->
			</xs:choice>
		</xs:sequence>
	</xs:group>
	<xs:group name="Comment_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="Comment">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:any minOccurs="0" maxOccurs="unbounded" />
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Graphic_">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Polyline">
					<xs:complexType>
						<xs:sequence>
							<xs:group ref="PointList_" />
						</xs:sequence>
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Line">
					<xs:complexType>
						<xs:sequence>
							<xs:group maxOccurs="2" ref="Point_" />
						</xs:sequence>
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Circle">
					<xs:complexType>
						<xs:attribute name="Radius" type="xs:unsignedByte" use="optional" />
						<xs:attributeGroup ref="AttributeXY_" />
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Pie">
					<xs:complexType>
						<xs:attribute name="X" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="Y" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="Radius" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="EndAngle" type="xs:string" use="optional" />
						<xs:attribute name="StartAngle" type="xs:string" use="optional" />
						<xs:attribute name="FillColor" type="xs:string" use="optional" />
						<xs:attribute name="LineColor" type="xs:string" use="optional" />
						<xs:attribute name="LineWidth" type="xs:unsignedByte" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Arc">
					<xs:complexType>
						<xs:attribute name="Radius" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="EndAngle" type="AttributeEquation" use="optional" />
						<xs:attribute name="StartAngle" type="AttributeEquation" use="optional" />
						<xs:attributeGroup ref="AttributeXY_" />
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Polygon">
					<xs:complexType>
						<xs:sequence>
							<xs:group ref="PointList_" />
						</xs:sequence>
						<xs:attribute name="FillColor" type="xs:string" use="optional" />
						<xs:attribute name="LineColor" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Image">
					<xs:complexType>
						<xs:sequence>
							<xs:choice minOccurs="0" maxOccurs="unbounded">
								<xs:element minOccurs="0" name="Transparent" type="xs:boolean" />
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string" />
					</xs:complexType>
				</xs:element>
				<xs:group minOccurs="0" maxOccurs="unbounded" ref="GaugeText_" />
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Rectangle">
					<xs:complexType>
						<xs:attribute name="Width" type="AttributeEquation" />
						<xs:attribute name="Height" type="AttributeEquation" />
						<xs:attribute name="Corner" type="AttributeEquation" />
						<xs:attribute name="CornerStyle" type="CornerStyle_" />
						<xs:attributeGroup ref="AttributeXY_" />
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:group>
	<xs:group name="KeyMap_">
		<xs:choice>
			<xs:element minOccurs="0" maxOccurs="1" name="KeyMap">
				<xs:complexType>
					<xs:group ref="Trigger_" />
				</xs:complexType>
			</xs:element>
			<xs:element minOccurs="0" maxOccurs="1" name="ActionMap">
				<xs:complexType>
					<xs:group ref="Trigger_" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="MouseArea_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="MouseArea">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:group ref="Position_" />
						<xs:group ref="Size_" />
						<xs:element minOccurs="1" maxOccurs="unbounded" name="MouseClick">
							<xs:complexType>
								<xs:sequence>
									<xs:choice>
										<xs:element minOccurs="0" name="KeyEvent" type="xs:string" />
										<xs:element name="Event" type="xs:string" />
									</xs:choice>
									<xs:group ref="Script_" />
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" use="optional" />
							</xs:complexType>
						</xs:element>
						<xs:group maxOccurs="1" ref="Visibility_" />
						<xs:group ref="MouseArea_" />
						<xs:group ref="Comment_" />
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Trigger_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="Trigger">
				<xs:complexType>
					<xs:sequence>
						<xs:choice>
							<xs:element name="KeyEvent" type="xs:string" />
							<xs:element name="Event" type="xs:string" />
						</xs:choice>
						<xs:element minOccurs="0" name="Script" type="Equation" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Position_">
		<xs:choice>
			<xs:element minOccurs="0" name="Position">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="Float2">
							<xs:attribute name="X" type="AttributeEquation" use="optional" />
							<xs:attribute name="Y" type="AttributeEquation" use="optional" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:choice>
				<xs:element minOccurs="0" name="FloatPosition" type="Float2" />
				<xs:element minOccurs="0" name="LeftScript" type="Equation" />
				<xs:element minOccurs="0" name="RightScript" type="Equation" />
			</xs:choice>
		</xs:choice>
	</xs:group>
	<xs:group name="Script_">
		<xs:sequence>
			<xs:element minOccurs="0" name="Script" type="Equation" />
		</xs:sequence>
	</xs:group>
	<xs:group name="Size_">
		<xs:choice>
			<xs:element minOccurs="0" name="Size">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="Float2" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="LineColor_">
		<xs:choice>
			<xs:element name="LineColor">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="Color_">
		<xs:choice>
			<xs:element name="Color">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="LineColorScript_">
		<xs:choice>
			<xs:element name="LineColorScript" type="Equation"/>
		</xs:choice>
	</xs:group>
	<xs:group name="Update_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="Update">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:group ref="Script_" />
							<xs:element minOccurs="0" name="Frequency" type="xs:float" />
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Visibility_">
		<xs:choice>
			<xs:element minOccurs="0" name="Visible" type="Equation" />
			<xs:element minOccurs="0" name="Visibility" type="Equation" />
		</xs:choice>
	</xs:group>
	<xs:group name="Point_">
		<xs:sequence>
			<xs:element name="Point">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="Float2">
							<xs:attributeGroup ref="AttributeXY_" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="PointList_">
		<xs:sequence>
			<xs:group maxOccurs="unbounded" ref="Point_" />
		</xs:sequence>
	</xs:group>
	<xs:group name="ElementContent_">
		<xs:sequence>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:group ref="Element_" />
				<xs:group ref="Position_" />
				<xs:group ref="Graphic_" />
				<xs:group ref="Visibility_" />
				<xs:group ref="Select_" />
				<xs:group ref="Choose_" />
				<xs:group ref="ForLoop_" />
				<xs:group ref="Rotation_" />
				<xs:group ref="Include_" />
				<xs:group ref="Shift_" />
			</xs:choice>
		</xs:sequence>
	</xs:group>
	<xs:group name="Element_">
		<xs:sequence>
			<xs:element name="Element">
				<xs:complexType>
					<xs:group ref="ElementContent_" />
					<xs:attribute name="id" type="xs:string" />
					<xs:attribute name="Context" type="Context_" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Expression_">
		<xs:sequence>
			<xs:element name="Expression">
				<xs:complexType>
					<xs:all>
						<xs:element minOccurs="0" maxOccurs="1" name="Minimum" type="xs:float" />
						<xs:element minOccurs="0" maxOccurs="1" name="Maximum" type="xs:float" />
						<xs:element minOccurs="1" maxOccurs="1" name="Script" type="Equation" />
					</xs:all>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Select_">
		<xs:sequence>
			<xs:element name="Select">
				<xs:complexType>
					<xs:sequence>
						<xs:group maxOccurs="1" ref="Expression_" />
						<xs:element minOccurs="1" maxOccurs="unbounded" name="Case">
							<xs:complexType>
								<xs:sequence>
									<xs:choice>
										<xs:element name="ExpressionResult" type="xs:string" />
										<xs:group ref="Expression_" />
									</xs:choice>
									<xs:group ref="ElementContent_" />
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" />
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" maxOccurs="1" name="CaseElse">
							<xs:complexType>
								<xs:group ref="ElementContent_" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Choose_">
		<xs:sequence>
			<xs:element name="Choose">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="1" maxOccurs="unbounded" name="When">
							<xs:complexType>
								<xs:sequence>
									<xs:choice>
										<xs:group ref="Expression_" />
									</xs:choice>
									<xs:group ref="ElementContent_" />
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" />
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" maxOccurs="1" name="Otherwise">
							<xs:complexType>
								<xs:group ref="ElementContent_" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="ForLoop_">
		<xs:sequence>
			<xs:element name="ForLoop">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="InitialExpression">
							<xs:complexType>
								<xs:group ref="Script_" />
							</xs:complexType>
						</xs:element>
						<xs:element name="TestExpression">
							<xs:complexType>
								<xs:group ref="Script_" />
							</xs:complexType>
						</xs:element>
						<xs:element name="IncrementExpression">
							<xs:complexType>
								<xs:group ref="Script_" />
							</xs:complexType>
						</xs:element>
						<xs:group ref="ElementContent_" />
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Value_">
		<xs:sequence>
			<xs:element name="Value" type="xs:string" />
		</xs:sequence>
	</xs:group>
	<xs:group name="GaugeText_">
		<xs:sequence>
			<xs:element name="GaugeText">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="1" maxOccurs="unbounded" name="String" type="xs:string" />
					</xs:sequence>
					<xs:attribute name="X" type="AttributeEquation" />
					<xs:attribute name="Y" type="AttributeEquation" />
					<xs:attribute name="Align" type="TextAlign_" />
					<xs:attribute name="VerticalAlign" type="TextVerticalAlign_" />
					<xs:attribute name="Font" type="xs:string" />
					<xs:attribute name="Height" type="xs:float" />
					<xs:attribute name="LineColor" type="AttributeEquation" />
					<xs:attribute name="Color" type="AttributeEquation" />
					<xs:attribute name="HaloColor" type="AttributeEquation" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:simpleType name="TextAlign_">
		<xs:restriction base="xs:string">
			<xs:enumeration value="center" />
			<xs:enumeration value="left" />
			<xs:enumeration value="right" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TextVerticalAlign_">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top" />
			<xs:enumeration value="middle" />
			<xs:enumeration value="center" />
			<xs:enumeration value="baseline" />
			<xs:enumeration value="bottom" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Context_" >
		<xs:restriction base="xs:string">
			<xs:enumeration value="group" />
			<xs:enumeration value="foreground" />
			<xs:enumeration value="background" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CornerStyle_">
		<xs:restriction base="xs:string">
			<xs:enumeration value="square" />
			<xs:enumeration value="bevel" />
			<xs:enumeration value="round" />
		</xs:restriction>
	</xs:simpleType>
	<xs:group name="Rotation_">
		<xs:sequence>
			<xs:element name="Rotation" type="Equation" />
		</xs:sequence>
	</xs:group>
	<xs:group name="Include_">
		<xs:sequence>
			<xs:element name="Include">
				<xs:complexType>
					<xs:attribute name="File" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Shift_">
		<xs:sequence>
			<xs:element name="Shift">
				<xs:complexType>
					<xs:attributeGroup ref="AttributeXY_" />
					<xs:attribute name="Maximum" type="AttributeEquation" />
					<xs:attribute name="Minimum" type="AttributeEquation" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
</xs:schema>

=== grizzie17/GS8/Config/gauges/button-quadrant.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="button-quadrant">
		<Update>
			<Script>
				(U:Current Quadrant Selected) s1
						(U:Feed 4 Position)
						(U:Feed 3 Position)
						(U:Feed 2 Position)
						(U:Feed 1 Position)
					4 (U:Current Quadrant Selected) case (=C:Edit Camera)
					0		// Do nothing
				(U:View Layout) (K:View Quad) == (U:BLACKOUT SELECTED) ! AND s0 ? both
			</Script>
		</Update>
		<Size>70,60</Size>
		<Element>
			<Include File="icon-quadrant" />
		</Element>
		<MouseArea id="MouseArea">
			<Visible>
        (U:View Layout) (K:View Quad) == (U:BLACKOUT SELECTED) ! AND
      </Visible>
			<FloatPosition>0.000,0.000</FloatPosition>
			<Size>70,60</Size>
			<MouseClick id="MouseClick">
				<KeyEvent>E:Change Camera Quadrant</KeyEvent>
			</MouseClick>
		</MouseArea>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/icon-temperature-coolant.xml
<?xml version="1.0" ?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="icon-temperature">
		<!--
		Registers are used to drive the various parameters
	
		NOTE: The gauge is green from bottom up.
		R5	- height of slider
		R6	- width of slider
		R7	- green separator (highest green reading)
		R8	- yellow separator (highest yellow reading)
		R9	- current position
		-->
		<Update>
			<Frequency>4</Frequency>
			<Script>
				(B:Engine Coolant Temp.Green.High) s7
				(B:Engine Coolant Temp.Yellow.High) s8 both
				(A:Engine Coolant Temp) s9 both

				/*
					Determine if the icon is to be displayed. If the temperature is below
				*/
					(U:FLASH)				// Yellow or Red reading, flash the gauge (false state will turn the gauge off)
					true								// else default to show gauge (based on the "visibility" tag below)
				r7 r9 &lt; ? s0
				both
			</Script>
		</Update>
		<Size>18,47</Size>
		<Element Context="foreground">
		<!--
		switch (U:GAUGE SWITCH)
		0:	if r9 > r7 then visible is true else false
		1:	visible is true
		2:	visible is false
		-->
		<Visibility>
			false
			r0
			r0 false r7 r9 &lt; 5 (A:RPM) &lt; AND ?
			3 (U:GAUGE SWITCH) case
			
		</Visibility>
			<Element>
				<Arc X="3 3 +" Y="3" 
					 Radius="3"
					 StartAngle="0" EndAngle="180" 
					 LineWidth="2" LineColor="(U:COLOR_IconSafe) (U:COLOR_IconAlert) (U:COLOR_IconWarning) r9 r8 &lt; ? r9 r7 &lt; ? s9"/>
				<Line LineWidth="2" LineColor="r9">
					<Point X="3" Y="3" />
					<Point X="3" Y="40" />
				</Line>
				<Line LineWidth="2" LineColor="r9">
					<Point X="3 6 +" Y="3" />
					<Point X="3 6 +" Y="40" />
				</Line>
				<Line LineWidth="1" LineColor="r9">
					<Point X="3 6 +" Y="7" />
					<Point X="3 15 +" Y="7" />
				</Line>
				<Line LineWidth="1" LineColor="r9">
					<Point X="3 6 +" Y="17" />
					<Point X="3 15 +" Y="17" />
				</Line>
				<Line LineWidth="1" LineColor="r9">
					<Point X="3 6 +" Y="27" />
					<Point X="3 15 +" Y="27" />
				</Line>
				<Circle X="3 3 +" Y="40" Radius="7" FillColor="r9"/>
				<Polygon LineColor="r9" FillColor="r9">
					<Point X="3" Y="14" />
					<Point X="3 6 +" Y="14" />
					<Point X="3 6 +" Y="40" />
					<Point X="3" Y="40" />
					<Point X="3" Y="14" />
				</Polygon>
			</Element>
			<Element>
				<Visibility>(U:GAUGE DETAIL)</Visibility>
				<GaugeText X="10" Y="50"
						   Font="Arial" Height="20" Align="center"
						   Color="r9" VerticalAlign="top">
					<String>%((A:Engine Coolant Temp) 'celsius' 'fahrenheit' 2 (U:UNITS) case unitcnv)%!d!</String>
				</GaugeText>
			</Element>
		</Element>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/LAV3_Event_Handlers_Camera_Select.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="LAV3_Event_Handlers_Camera_Select">
		<ActionMap>
      <Trigger>
        <KeyEvent>E:CAMERA SELECT</KeyEvent>
        <Script>
          (U:CAMERA SELECT ACTIVE) ! (=U:CAMERA SELECT ACTIVE)
        </Script>
      </Trigger>
			<Trigger>
				<KeyEvent>E:CAMERA SELECT RIGHT</KeyEvent>
				<Script>
          (S:MILLI) (=U:Camera RIGHT Timeout)
          (K:RIGHT) (=E:Change Camera Feed) both
        </Script>
			</Trigger>
			<Trigger>
				<KeyEvent>E:CAMERA SELECT LEFT</KeyEvent>
				<Script>
          (S:MILLI) (=U:Camera LEFT Timeout)
          (K:LEFT) (=E:Change Camera Feed) both
        </Script>
			</Trigger>
			<Trigger>
				<KeyEvent>E:CAMERA SELECT UP</KeyEvent>
				<Script>
          (S:MILLI) (=U:Camera UP Timeout)
          (K:UP) (=E:Change Camera Feed) both
        </Script>
			</Trigger>
			<Trigger>
				<KeyEvent>E:CAMERA SELECT DOWN</KeyEvent>
				<Script>
          (S:MILLI) (=U:Camera DOWN Timeout)
          (K:DOWN) (=E:Change Camera Feed) both
        </Script>
			</Trigger>
		<Trigger>
			<Event>E:Change Camera Feed</Event>
			<Script>
					(E:Change Camera Feed) (=E:Change Camera Feed SINGLE View)
						(E:Change Camera Feed) (=E:Change Camera Feed QUAD View)
						(E:Change Camera Feed) (=E:Change Camera Feed PIP View)
						""
						(U:View Layout) (K:View PIP) == ?
					(U:View Layout) (K:View Quad) == ?
				(U:View Layout) (K:View Single) == ?
			</Script>
		</Trigger>
		<Trigger>
			<Event>E:Change Camera Feed SINGLE View</Event>
			<Script>
				(E:Change Camera Feed SINGLE View) (=E:Change Camera Feed 1)
			</Script>
		</Trigger>
		<Trigger>
			<Event>E:Change Camera Feed PIP View</Event>
			<Script>
					(E:Change Camera Feed PIP View) (=E:Change Camera Feed 1)
					(E:Change Camera Feed PIP View) (=E:Change Camera Feed 2)
				2 (U:Current PIP Selected) case
			</Script>
		</Trigger>
		<Trigger>
			<Event>E:Change Camera Feed QUAD View</Event>
			<Script>
					(E:Change Camera Feed QUAD View) (=E:Change Camera Feed 1)
						(E:Change Camera Feed QUAD View) (=E:Change Camera Feed 2)
							(E:Change Camera Feed QUAD View) (=E:Change Camera Feed 3)
								(E:Change Camera Feed QUAD View) (=E:Change Camera Feed 4)
								false
							3 (U:Current Quadrant Selected) == ?
						2 (U:Current Quadrant Selected) == ?
					1 (U:Current Quadrant Selected) == ?
				0 (U:Current Quadrant Selected) == ?
			</Script>
		</Trigger>
		<Trigger>
			<Event>E:Change Camera Feed 1</Event>
			<Script>
			"Video Feed 1" (=U:Current Video Feed)
			(E:Change Camera Feed 1) "C:Selector " (D:Camera Selector) + =@
			both
			</Script>
		</Trigger>
		<Trigger>
			<Event>E:Change Camera Feed 2</Event>
			<Script>
			"Video Feed 2" (=U:Current Video Feed)
			(E:Change Camera Feed 2) "C:Selector " (D:Camera Selector) + =@
			both
			</Script>
		</Trigger>
		<Trigger>
			<Event>E:Change Camera Feed 3</Event>
			<Script>
			"Video Feed 3" (=U:Current Video Feed)
			(E:Change Camera Feed 3) "C:Selector " (D:Camera Selector) + =@
			both
			</Script>
		</Trigger>
		<Trigger>
			<Event>E:Change Camera Feed 4</Event>
			<Script>
			"Video Feed 4" (=U:Current Video Feed)
			(E:Change Camera Feed 4) "C:Selector " (D:Camera Selector) + =@
			both
			</Script>
		</Trigger>
		</ActionMap>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/button-quadrant_adjust_camera.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="button-quadrant_adjust_camera">
		<Update>
			<Script>
					0
					(U:Current Adjust Quadrant Selected)
				"" (U:Current Adjust Quadrant Selected) == ? s1
				(U:View Layout) (K:View Quad) == (U:BLACKOUT SELECTED) ! AND s0
				both
			</Script>
		</Update>
		<Size>70,60</Size>
		<Element>
			<Include File="icon-quadrant" />
		</Element>
		<MouseArea id="MouseArea">
			<Visible>
				(U:View Layout) (K:View Quad) == (U:BLACKOUT SELECTED) ! AND
			</Visible>
			<FloatPosition>0.000,0.000</FloatPosition>
			<Size>70,60</Size>
			<MouseClick id="MouseClick">
				<KeyEvent>E:Change Camera Adjust Quadrant</KeyEvent>
			</MouseClick>
		</MouseArea>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/button-camera-edit.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="button-camera_edit">
		<Update>
			<Script>
				'Exit'
				'Adjust'
				(U:CAMERA EDIT SELECTED) ? (=G:EditLabel)
			</Script>
		</Update>
		<Size>60,50</Size>
		<Element>
			<Visible>(U:BLACKOUT SELECTED) !</Visible>
			<GaugeText X="0" Y="0" Font="sans-serif" Height="20" Align="left" VerticalAlign="top" Color="'gold' 'lime' (U:CAMERA EDIT SELECTED) ? s0">
				<String>%( (G:EditLabel) )%!s!</String>
			</GaugeText>
			<GaugeText X="0" Y="20" Font="sans-serif" Height="20" Align="left" VerticalAlign="top" Color="r0">
				<String>Camera</String>
			</GaugeText>
			<!--GaugeText X="0" Y="40" Font="sans-serif" Height="20" Align="left" VerticalAlign="top" Color="r0">
				<String>Settings</String>
			</GaugeText-->
		</Element>
		<MouseArea id="MouseArea">
			<FloatPosition>0.000,0.000</FloatPosition>
			<Size>60,50</Size>
			<MouseClick id="MouseClick">
				<KeyEvent>E:TOGGLE CAMERA SETTINGS</KeyEvent>
			</MouseClick>
		</MouseArea>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/NVL_Sub_Menu_Entry_3.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="NVL_Sub_Menu_Entry_3">

		<Update>
			<Script>
				2 s7
				0x00FF00 s1 both
			</Script>
		</Update>

		<Size>130,20</Size>
		<Element>
			<Select>
				<Expression>
					<Script>(U:Main Menu Ptr)</Script>
				</Expression>
				<Case>
					<Expression>
						<Script>(K:Main Menu ID SCREEN MODE)</Script>
					</Expression>
					<Include File="NVL_Sub_Menu_Items_Screen_Mode"/>
				</Case>
				<Case>
					<Expression>
						<Script>(K:Main Menu ID CAMERA SETTINGS)</Script>
					</Expression>
					<Include File="NVL_Sub_Menu_Items_Camera_Settings"/>
				</Case>
				<Case>
					<Expression>
						<Script>(K:Main Menu ID QUADRANT)</Script>
					</Expression>
					<Include File="NVL_Sub_Menu_Items_Quadrant"/>
				</Case>
				<Case>
					<Expression>
						<Script>(K:Main Menu ID MISC)</Script>
					</Expression>
					<Include File="NVL_Sub_Menu_Items_Misc"/>
				</Case>
				<Case>
					<Expression>
						<Script>(K:Main Menu ID EXIT)</Script>
					</Expression>
					<Include File="NVL_Sub_Menu_Items_Exit"/>
				</Case>
			</Select>
		</Element>
		<MouseArea id="MouseArea">
			<Visible>
				TRUE
			</Visible>
			<FloatPosition>0.000,0.000</FloatPosition>
			<Size>130,20</Size>
			<MouseClick id="MouseClick">
				<KeyEvent></KeyEvent>
			</MouseClick>
		</MouseArea>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/NVL_Main_Menu_Entry_Label.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="NVL_Main_Menu_Entry_Label">
		<Update>
			<Script>
				1 s0
				"Quadrant" s6 both
				0x00FF00 s1 both
			</Script>
		</Update>
		<Size>50,10</Size>
		<Element>
			<Include File="menu_item" />
		</Element>
		<MouseArea id="MouseArea">
			<Visible>
				TRUE
			</Visible>
			<FloatPosition>0.000,0.000</FloatPosition>
			<Size>50,10</Size>
			<MouseClick id="MouseClick">
				<KeyEvent>E:Change Camera Feed</KeyEvent>
			</MouseClick>
		</MouseArea>
	</SimGauge.Gauge>
</SimBase.Document>
