=== grizzie17/GS8/Config/gauges/Gauges.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="SimBase.Document">
		<xs:complexType>
			<xs:all>
				<xs:element minOccurs="1" maxOccurs="1" name="SimGauge.Gauge">
					<xs:complexType>
						<xs:group ref="GaugeContent_" />
						<xs:attribute name="id" type="xs:string" use="optional" />
						<xs:attribute name="Name" type="xs:string" />
						<xs:attribute name="Crop" type="xs:boolean" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" name="Descr" type="xs:string" />
			</xs:all>
			<xs:attribute name="Type" type="xs:string" use="optional" />
			<xs:attribute name="version" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="Gauge">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="GaugeContent_" />
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" />
			<xs:attribute name="Version" type="xs:float" />
			<xs:attribute name="Crop" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="Float2">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="Equation">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="AttributeEquation">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:attributeGroup name="AttributeStyle_">
		<xs:attribute name="Color" type="AttributeEquation" />
		<xs:attribute name="LineColor" type="AttributeEquation" />
		<xs:attribute name="FillColor" type="AttributeEquation" />
		<xs:attribute name="LineWidth" type="AttributeEquation" />
		<xs:attribute name="HaloColor" type="AttributeEquation" />
	</xs:attributeGroup>
	<xs:attributeGroup name="AttributeXY_">
		<xs:attribute name="X" type="AttributeEquation" />
		<xs:attribute name="Y" type="AttributeEquation" />
	</xs:attributeGroup>
	<xs:group name="GaugeContent_">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group minOccurs="0" maxOccurs="1" ref="Position_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Size_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Element_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Update_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="MouseArea_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="KeyMap_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Comment_" />
				<!--xs:group minOccurs="0" maxOccurs="1" ref="Visibility_" /-->
			</xs:choice>
		</xs:sequence>
	</xs:group>
	<xs:group name="Comment_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="Comment">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:any minOccurs="0" maxOccurs="unbounded" />
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Graphic_">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Polyline">
					<xs:complexType>
						<xs:sequence>
							<xs:group ref="PointList_" />
						</xs:sequence>
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Line">
					<xs:complexType>
						<xs:sequence>
							<xs:group maxOccurs="2" ref="Point_" />
						</xs:sequence>
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Circle">
					<xs:complexType>
						<xs:attribute name="Radius" type="xs:unsignedByte" use="optional" />
						<xs:attributeGroup ref="AttributeXY_" />
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Pie">
					<xs:complexType>
						<xs:attribute name="X" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="Y" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="Radius" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="EndAngle" type="xs:string" use="optional" />
						<xs:attribute name="StartAngle" type="xs:string" use="optional" />
						<xs:attribute name="FillColor" type="xs:string" use="optional" />
						<xs:attribute name="LineColor" type="xs:string" use="optional" />
						<xs:attribute name="LineWidth" type="xs:unsignedByte" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Arc">
					<xs:complexType>
						<xs:attribute name="Radius" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="EndAngle" type="AttributeEquation" use="optional" />
						<xs:attribute name="StartAngle" type="AttributeEquation" use="optional" />
						<xs:attributeGroup ref="AttributeXY_" />
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Polygon">
					<xs:complexType>
						<xs:sequence>
							<xs:group ref="PointList_" />
						</xs:sequence>
						<xs:attribute name="FillColor" type="xs:string" use="optional" />
						<xs:attribute name="LineColor" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Image">
					<xs:complexType>
						<xs:sequence>
							<xs:choice minOccurs="0" maxOccurs="unbounded">
								<xs:element minOccurs="0" name="Transparent" type="xs:boolean" />
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string" />
					</xs:complexType>
				</xs:element>
				<xs:group minOccurs="0" maxOccurs="unbounded" ref="GaugeText_" />
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Rectangle">
					<xs:complexType>
						<xs:attribute name="Width" type="AttributeEquation" />
						<xs:attribute name="Height" type="AttributeEquation" />
						<xs:attribute name="Corner" type="AttributeEquation" />
						<xs:attribute name="CornerStyle" type="CornerStyle_" />
						<xs:attributeGroup ref="AttributeXY_" />
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:group>
	<xs:group name="KeyMap_">
		<xs:choice>
			<xs:element minOccurs="0" maxOccurs="1" name="KeyMap">
				<xs:complexType>
					<xs:group ref="Trigger_" />
				</xs:complexType>
			</xs:element>
			<xs:element minOccurs="0" maxOccurs="1" name="ActionMap">
				<xs:complexType>
					<xs:group ref="Trigger_" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="MouseArea_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="MouseArea">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:group ref="Position_" />
						<xs:group ref="Size_" />
						<xs:element minOccurs="1" maxOccurs="unbounded" name="MouseClick">
							<xs:complexType>
								<xs:sequence>
									<xs:choice>
										<xs:element minOccurs="0" name="KeyEvent" type="xs:string" />
										<xs:element name="Event" type="xs:string" />
									</xs:choice>
									<xs:group ref="Script_" />
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" use="optional" />
							</xs:complexType>
						</xs:element>
						<xs:group maxOccurs="1" ref="Visibility_" />
						<xs:group ref="MouseArea_" />
						<xs:group ref="Comment_" />
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Trigger_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="Trigger">
				<xs:complexType>
					<xs:sequence>
						<xs:choice>
							<xs:element name="KeyEvent" type="xs:string" />
							<xs:element name="Event" type="xs:string" />
						</xs:choice>
						<xs:element minOccurs="0" name="Script" type="Equation" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Position_">
		<xs:choice>
			<xs:element minOccurs="0" name="Position">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="Float2">
							<xs:attribute name="X" type="AttributeEquation" use="optional" />
							<xs:attribute name="Y" type="AttributeEquation" use="optional" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:choice>
				<xs:element minOccurs="0" name="FloatPosition" type="Float2" />
				<xs:element minOccurs="0" name="LeftScript" type="Equation" />
				<xs:element minOccurs="0" name="RightScript" type="Equation" />
			</xs:choice>
		</xs:choice>
	</xs:group>
	<xs:group name="Script_">
		<xs:sequence>
			<xs:element minOccurs="0" name="Script" type="Equation" />
		</xs:sequence>
	</xs:group>
	<xs:group name="Size_">
		<xs:choice>
			<xs:element minOccurs="0" name="Size">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="Float2" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="LineColor_">
		<xs:choice>
			<xs:element name="LineColor">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="Color_">
		<xs:choice>
			<xs:element name="Color">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="LineColorScript_">
		<xs:choice>
			<xs:element name="LineColorScript" type="Equation"/>
		</xs:choice>
	</xs:group>
	<xs:group name="Update_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="Update">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:group ref="Script_" />
							<xs:element minOccurs="0" name="Frequency" type="xs:float" />
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Visibility_">
		<xs:choice>
			<xs:element minOccurs="0" name="Visible" type="Equation" />
			<xs:element minOccurs="0" name="Visibility" type="Equation" />
		</xs:choice>
	</xs:group>
	<xs:group name="Point_">
		<xs:sequence>
			<xs:element name="Point">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="Float2">
							<xs:attributeGroup ref="AttributeXY_" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="PointList_">
		<xs:sequence>
			<xs:group maxOccurs="unbounded" ref="Point_" />
		</xs:sequence>
	</xs:group>
	<xs:group name="ElementContent_">
		<xs:sequence>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:group ref="Element_" />
				<xs:group ref="Position_" />
				<xs:group ref="Graphic_" />
				<xs:group ref="Visibility_" />
				<xs:group ref="Select_" />
				<xs:group ref="Choose_" />
				<xs:group ref="ForLoop_" />
				<xs:group ref="Rotation_" />
				<xs:group ref="Include_" />
				<xs:group ref="Shift_" />
			</xs:choice>
		</xs:sequence>
	</xs:group>
	<xs:group name="Element_">
		<xs:sequence>
			<xs:element name="Element">
				<xs:complexType>
					<xs:group ref="ElementContent_" />
					<xs:attribute name="id" type="xs:string" />
					<xs:attribute name="Context" type="Context_" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Expression_">
		<xs:sequence>
			<xs:element name="Expression">
				<xs:complexType>
					<xs:all>
						<xs:element minOccurs="0" maxOccurs="1" name="Minimum" type="xs:float" />
						<xs:element minOccurs="0" maxOccurs="1" name="Maximum" type="xs:float" />
						<xs:element minOccurs="1" maxOccurs="1" name="Script" type="Equation" />
					</xs:all>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Select_">
		<xs:sequence>
			<xs:element name="Select">
				<xs:complexType>
					<xs:sequence>
						<xs:group maxOccurs="1" ref="Expression_" />
						<xs:element minOccurs="1" maxOccurs="unbounded" name="Case">
							<xs:complexType>
								<xs:sequence>
									<xs:choice>
										<xs:element name="ExpressionResult" type="xs:string" />
										<xs:group ref="Expression_" />
									</xs:choice>
									<xs:group ref="ElementContent_" />
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" />
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" maxOccurs="1" name="CaseElse">
							<xs:complexType>
								<xs:group ref="ElementContent_" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Choose_">
		<xs:sequence>
			<xs:element name="Choose">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="1" maxOccurs="unbounded" name="When">
							<xs:complexType>
								<xs:sequence>
									<xs:choice>
										<xs:group ref="Expression_" />
									</xs:choice>
									<xs:group ref="ElementContent_" />
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" />
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" maxOccurs="1" name="Otherwise">
							<xs:complexType>
								<xs:group ref="ElementContent_" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="ForLoop_">
		<xs:sequence>
			<xs:element name="ForLoop">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="InitialExpression">
							<xs:complexType>
								<xs:group ref="Script_" />
							</xs:complexType>
						</xs:element>
						<xs:element name="TestExpression">
							<xs:complexType>
								<xs:group ref="Script_" />
							</xs:complexType>
						</xs:element>
						<xs:element name="IncrementExpression">
							<xs:complexType>
								<xs:group ref="Script_" />
							</xs:complexType>
						</xs:element>
						<xs:group ref="ElementContent_" />
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Value_">
		<xs:sequence>
			<xs:element name="Value" type="xs:string" />
		</xs:sequence>
	</xs:group>
	<xs:group name="GaugeText_">
		<xs:sequence>
			<xs:element name="GaugeText">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="1" maxOccurs="unbounded" name="String" type="xs:string" />
					</xs:sequence>
					<xs:attribute name="X" type="AttributeEquation" />
					<xs:attribute name="Y" type="AttributeEquation" />
					<xs:attribute name="Align" type="TextAlign_" />
					<xs:attribute name="VerticalAlign" type="TextVerticalAlign_" />
					<xs:attribute name="Font" type="xs:string" />
					<xs:attribute name="Height" type="xs:float" />
					<xs:attribute name="LineColor" type="AttributeEquation" />
					<xs:attribute name="Color" type="AttributeEquation" />
					<xs:attribute name="HaloColor" type="AttributeEquation" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:simpleType name="TextAlign_">
		<xs:restriction base="xs:string">
			<xs:enumeration value="center" />
			<xs:enumeration value="left" />
			<xs:enumeration value="right" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TextVerticalAlign_">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top" />
			<xs:enumeration value="middle" />
			<xs:enumeration value="center" />
			<xs:enumeration value="baseline" />
			<xs:enumeration value="bottom" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Context_" >
		<xs:restriction base="xs:string">
			<xs:enumeration value="group" />
			<xs:enumeration value="foreground" />
			<xs:enumeration value="background" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CornerStyle_">
		<xs:restriction base="xs:string">
			<xs:enumeration value="square" />
			<xs:enumeration value="bevel" />
			<xs:enumeration value="round" />
		</xs:restriction>
	</xs:simpleType>
	<xs:group name="Rotation_">
		<xs:sequence>
			<xs:element name="Rotation" type="Equation" />
		</xs:sequence>
	</xs:group>
	<xs:group name="Include_">
		<xs:sequence>
			<xs:element name="Include">
				<xs:complexType>
					<xs:attribute name="File" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Shift_">
		<xs:sequence>
			<xs:element name="Shift">
				<xs:complexType>
					<xs:attributeGroup ref="AttributeXY_" />
					<xs:attribute name="Maximum" type="AttributeEquation" />
					<xs:attribute name="Minimum" type="AttributeEquation" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
</xs:schema>

=== grizzie17/GS8/Config/gauges/icon-up-arrow.xml
<?xml version="1.0"?>
<Gauge Name="icon-up-arrow" Version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<Size>65,45</Size>
	<Element Context="background">
		<!--
			All icon files utlize the registers to pass color information. The current register assignment is as follows:
			r0 defines the visiblity of the icon
			r1..r5 defines the color palet (It is not required to utlize all of the registers)
			-->
		<Visible>r0</Visible>
		<Polygon LineColor="r1" FillColor="r2">
			<Point X="20" Y="0"/>
			<Point X="35" Y="40"/>
			<Point X="5" Y="40"/>
			<Point X="20" Y="0"/>
		</Polygon>
	</Element>
</Gauge>

=== grizzie17/GS8/Config/gauges/MPC_monitor_edit_camera_events.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="MPC_monitor_edit_camera_events">
		<ActionMap>
			<!--
			=========================================================
			This event will toggle the shutter state.
			NOTE: Currently not supported by the Client.
			==========================================================
			-->
			<Trigger>
				<KeyEvent>E:TOGGLE SHUTTER</KeyEvent>
				<Script>
					(U:SHUTTER OPEN SELECTED) ! (=U:SHUTTER OPEN SELECTED)
				</Script>
			</Trigger>
			<!--
			=========================================================
			This event will start a timer for the One point Cal in the pressed state.
			The pressed states are DOWN and UP. If the buttone is pressed for a
			duration greater than a prescribed time then the AUTO/MAN mode is
			toggled. Else a one point cal is performed.
			==========================================================
			-->
			<Trigger>
				<KeyEvent>E:CLICK ONE POINT CAL DOWN</KeyEvent>
				<Script>
					(S:MILLI) 300 + (=U:OnePtCal Mode Change Timeout)
					true (=U:OnePtCal DOWN Button Active)
					both
				</Script>
			</Trigger>
			<Trigger>
				<KeyEvent>E:CLICK ONE POINT CAL UP</KeyEvent>
				<!--
				If the One Point Cal toggle button was pressed for less than the
				prescribed time it takes to toggle the states (MAN/AUTO) then it
				is assumed that a one point cal is to occur. Set the flash flash
				timeout duration.
				-->
				<Script>
					true (=U:OnePtCal DOWN Button Released)
				</Script>
			</Trigger>
			<!--
			=========================================================
			This event will toggle the calibration setting and output command to camera
			NOTE: If this event is generated then it indicates the adjust/edit function is
			available. Hence no need to check for "K:Unsupported"
			==========================================================
			-->
			<Trigger>
				<KeyEvent>E:TOGGLE CALIBRATION</KeyEvent>
				<Script>
					(U:AUTO CAL SELECTED) ! (=U:AUTO CAL SELECTED)


					(S:MILLI) 300 + (=U:Blink Calibration Timeout) both

					// Support Control or Toggle only.
					(K:On) (K:Off) (U:AUTO CAL SELECTED) ?
					(K:Toggle)
					(K:Control) (D:Camera Cap Auto Calibration) == ? (=C:Camera Auto Calibration)

					both

				</Script>
			</Trigger>
			<!--
			=========================================================
			This event will set the camera polarity
			NOTE: If this event is generated then it indicates the adjust/edit function is
			available. Hence no need to check for "K:Unsupported"
			==========================================================
			-->
			<Trigger>
				<KeyEvent>E:TOGGLE POLARITY</KeyEvent>
				<Script>
					(U:BLACK POLARITY SELECTED) ! (=U:BLACK POLARITY SELECTED)

					(K:Black) (K:White) (U:BLACK POLARITY SELECTED) ?
					(K:Toggle)
					(K:Control) (D:Camera Cap Polarity) == ? (=C:Camera Polarity)
					both

					(S:MILLI) 300 + (=U:Blink Polarity Timeout) both
					0 (=U:ADJUST ACTIVE) both
				</Script>
			</Trigger>
			<!--
			=========================================================
			This event will set the camera polarity
			NOTE: If this event is generated then it indicates the adjust/edit function is
			available. Hence no need to check for "K:Unsupported"
			==========================================================
			-->
			<Trigger>
				<KeyEvent>E:TOGGLE IR CAMERA MODE</KeyEvent>
				<Script>

					(K:LAP)	(K:Toggle) (K:Control) (D:Camera Cap Mode Control) == ? (=C:Camera Mode Control)
					0 (=U:ADJUST ACTIVE) both

					(S:MILLI) 300 + (=U:Blink IR Mode Timeout) both

				</Script>
			</Trigger>
			<!--
			=========================================================
			This event will toggle the enable function
			TBD, this button supports only ZOOM at this time. It needs to be generic
			NOTE: If this event is generated then it indicates the adjust/edit function is
			available. Hence no need to check for "K:Unsupported"
			==========================================================
			-->
			<Trigger>
				<KeyEvent>E:TOGGLE ENABLE</KeyEvent>
				<Script>
					(U:ZOOM ENABLE SELECTED) ! (=U:ZOOM ENABLE SELECTED)

					(K:On) (K:Off) (U:ZOOM ENABLE SELECTED) ?
					(K:Toggle)
					(K:Control) (D:Camera Cap Zoom Mode) == ? (=C:Camera Zoom Mode)
					both

					(S:MILLI) 300 + (=U:Zoom Toggle Timeout)
					both
				</Script>
			</Trigger>
			<!--
			=========================================================
			This event will output camera adjust command for the UP arrow.
			==========================================================
			-->
			<Trigger>
				<KeyEvent>E:UP SELECTED</KeyEvent>
				<!--
				The local variable G:Timeout is utilized to blink the UP selection
				-->
				<Script>
					(K:Increase) (=C:Camera Sharpness)

						(K:Increase) (=C:Camera Zoom)

							(K:Increase) (=C:Camera Contrast)

								(K:Increase) (=C:Camera Brightness)
								false
								'Bright' (U:EDIT BUTTON SELECTED) == ?

							'Cntrst' (U:EDIT BUTTON SELECTED) == ?

						'Zoom' (U:EDIT BUTTON SELECTED) == ?

					'Sharp' (U:EDIT BUTTON SELECTED) == ?

					'UP' (=U:THE DIRECTION PRESSED)						// This is not required, for debug only
					both

					(S:MILLI) 300 + (=U:UP Timeout)
					both
				</Script>
			</Trigger>
			<!--
			=========================================================
			This event will output camera adjust command for the DOWN arrow.
			==========================================================
			-->
			<Trigger>
				<KeyEvent>E:DOWN SELECTED</KeyEvent>
				<!--
				The local variable G:Timeout is utilized to blink the DOWN selection
				-->
				<Script>
					(K:Decrease) (=C:Camera Sharpness)

						(K:Decrease) (=C:Camera Zoom)

							(K:Decrease) (=C:Camera Contrast)

								(K:Decrease) (=C:Camera Brightness)
								false
								'Bright' (U:EDIT BUTTON SELECTED) == ?

							'Cntrst' (U:EDIT BUTTON SELECTED) == ?

						'Zoom' (U:EDIT BUTTON SELECTED) == ?

					'Sharp' (U:EDIT BUTTON SELECTED) == ?

					'DOWN' (=U:THE DIRECTION PRESSED)					// This is not required, for debug only
					both

					(S:MILLI) 300 + (=U:DOWN Timeout)
					both
				</Script>
			</Trigger>
			<!--
			=========================================================
			This event will
			==========================================================
			-->
			<!--
			=========================================================
			This event will
			==========================================================
			-->
			<!--
			This event initiates the camera adjustment (edit) panel
			-->
			<Trigger>
				<KeyEvent>E:TOGGLE ADJUST CAMERA SETTINGS</KeyEvent>
				<Script>
					(U:CAMERA ADJUST SELECTED) ! (=U:CAMERA ADJUST SELECTED)
					0 (=U:ADJUST ACTIVE) both
					2 (=E:UPDATE ADJUST PAGE)
					both
				</Script>
			</Trigger>
			<!--
			=========================================================
			This event will
			==========================================================
			-->
			<Trigger>
				<KeyEvent>E:DISABLE ADJUST CAMERA SETTINGS</KeyEvent>
				<Script>
					0 (=U:CAMERA ADJUST SELECTED)
					2 (=E:UPDATE ADJUST PAGE)
					both
				</Script>
			</Trigger>
			<!--
			=========================================================
			This event will
			==========================================================
			-->
			<Trigger>
				<KeyEvent>E:TOGGLE DAYNIGHT</KeyEvent>
				<Script>
          (U:DAY SELECTED) ! (=U:DAY SELECTED)
          1 (=E:SET VIDEO FEED)	both
          1 (=E:SET SINGLE VIDEO FEED) both
        </Script>
			</Trigger>
		</ActionMap>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/rotary.xml
<?xml version="1.0" ?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="rotary" Crop="true">
		<Size>220,100</Size>
		<!--<Size>220,228</Size>-->
		<Element>
			<Position X="110" Y="160" />
			<Element Context="background">
				<Visible>(G:HIDE/SHOW) !</Visible>
				<Pie X="0" Y="0" Radius="150" StartAngle="180 0.25 * s0" EndAngle="180 0.75 * s1" FillColor="gray" LineColor="gray" LineWidth="2" />
				<Pie X="0" Y="0" Radius="150" StartAngle="r1 180 0.5 * (T:SLIDER.YELLOW) 100 / * - s2" EndAngle="r1" FillColor="green" LineColor="white" LineWidth="2" />
				<Pie X="0" Y="0" Radius="150" StartAngle="r1 180 0.5 * (T:SLIDER.RED) 100 / * - s3" EndAngle="r2" FillColor="gold" LineColor="white" LineWidth="2" />
				<Pie X="0" Y="0" Radius="150" StartAngle="r0" EndAngle="l3" FillColor="red" LineColor="white" LineWidth="2" />
				<Pie X="0" Y="0" Radius="120" StartAngle="r0 2 -" EndAngle="r1 2 +" FillColor="background" LineColor="background" LineWidth="2" />
				<Arc X="0" Y="0" Radius="120" StartAngle="r0" EndAngle="r1" LineColor="white" LineWidth="2" />
			</Element>
			<Element Context="foreground">
				<Element>
					<Position X="6" Y="6" />
					<Rotation>r1 180 0.5 * (T:PULSER) 100 / * - s5</Rotation>
					<Polygon FillColor="black">
						<Point X="30" Y="0" />
						<Point X="28" Y="-10" />
						<Point X="153" Y="-2" />
						<Point X="155" Y="0" />
						<Point X="153" Y="2" />
						<Point X="28" Y="10" />
						<Point X="30" Y="0" />
					</Polygon>
				</Element>
				<Circle X="0" Y="0" Radius="30" FillColor="gray" LineColor="lightgray" LineWidth="8" />
				<Element>
					<Rotation>r5</Rotation>
					<Polygon FillColor="darkred">
						<Point X="30" Y="0" />
						<Point X="28" Y="-10" />
						<Point X="153" Y="-2" />
						<Point X="155" Y="0" />
						<Point X="153" Y="2" />
						<Point X="28" Y="10" />
						<Point X="30" Y="0" />
					</Polygon>
					<Polygon FillColor="red" LineColor="darkred">
						<Point X="30" Y="0" />
						<Point X="28" Y="-10" />
						<Point X="153" Y="-2" />
						<Point X="155" Y="0" />
						<Point X="30" Y="0" />
					</Polygon>
				</Element>
			</Element>
		</Element>
		<KeyMap>
			<Trigger>
				<KeyEvent>E:ROTARY HIDE/SHOW</KeyEvent>
				<Script>(G:HIDE/SHOW) ! (&gt;G:HIDE/SHOW)</Script>
			</Trigger>
		</KeyMap>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/button-adjust-up.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="button-adjust-up">
		<Update>
			<Script>
				0x004000 0x00FF00 (S:MILLI) (U:UP Timeout) &gt; ? s2
				0x00FF00 s1
				both
				(U:BLACKOUT SELECTED) ! (U:ADJUST ACTIVE) AND s0
				both
			</Script>
		</Update>
		<Size>70,40</Size>
		<Element Context="background">
			<Include File="icon-up-arrow" />
		</Element>
	<MouseArea id="MouseArea">
		<FloatPosition>0.000,0.000</FloatPosition>
		<Size>70,40</Size>
		<MouseClick id="MouseClick">
			<KeyEvent>E:UP SELECTED</KeyEvent>
		</MouseClick>
	</MouseArea>
	</SimGauge.Gauge>
</SimBase.Document>
