=== grizzie17/GS8/Config/gauges/Gauges.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="SimBase.Document">
		<xs:complexType>
			<xs:all>
				<xs:element minOccurs="1" maxOccurs="1" name="SimGauge.Gauge">
					<xs:complexType>
						<xs:group ref="GaugeContent_" />
						<xs:attribute name="id" type="xs:string" use="optional" />
						<xs:attribute name="Name" type="xs:string" />
						<xs:attribute name="Crop" type="xs:boolean" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" name="Descr" type="xs:string" />
			</xs:all>
			<xs:attribute name="Type" type="xs:string" use="optional" />
			<xs:attribute name="version" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="Gauge">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="GaugeContent_" />
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" />
			<xs:attribute name="Version" type="xs:float" />
			<xs:attribute name="Crop" type="xs:boolean" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="Float2">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="Equation">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="AttributeEquation">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:attributeGroup name="AttributeStyle_">
		<xs:attribute name="Color" type="AttributeEquation" />
		<xs:attribute name="LineColor" type="AttributeEquation" />
		<xs:attribute name="FillColor" type="AttributeEquation" />
		<xs:attribute name="LineWidth" type="AttributeEquation" />
		<xs:attribute name="HaloColor" type="AttributeEquation" />
	</xs:attributeGroup>
	<xs:attributeGroup name="AttributeXY_">
		<xs:attribute name="X" type="AttributeEquation" />
		<xs:attribute name="Y" type="AttributeEquation" />
	</xs:attributeGroup>
	<xs:group name="GaugeContent_">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:group minOccurs="0" maxOccurs="1" ref="Position_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Size_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Element_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Update_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="MouseArea_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="KeyMap_" />
				<xs:group minOccurs="0" maxOccurs="1" ref="Comment_" />
				<!--xs:group minOccurs="0" maxOccurs="1" ref="Visibility_" /-->
			</xs:choice>
		</xs:sequence>
	</xs:group>
	<xs:group name="Comment_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="Comment">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:any minOccurs="0" maxOccurs="unbounded" />
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Graphic_">
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Polyline">
					<xs:complexType>
						<xs:sequence>
							<xs:group ref="PointList_" />
						</xs:sequence>
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Line">
					<xs:complexType>
						<xs:sequence>
							<xs:group maxOccurs="2" ref="Point_" />
						</xs:sequence>
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Circle">
					<xs:complexType>
						<xs:attribute name="Radius" type="xs:unsignedByte" use="optional" />
						<xs:attributeGroup ref="AttributeXY_" />
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Pie">
					<xs:complexType>
						<xs:attribute name="X" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="Y" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="Radius" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="EndAngle" type="xs:string" use="optional" />
						<xs:attribute name="StartAngle" type="xs:string" use="optional" />
						<xs:attribute name="FillColor" type="xs:string" use="optional" />
						<xs:attribute name="LineColor" type="xs:string" use="optional" />
						<xs:attribute name="LineWidth" type="xs:unsignedByte" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Arc">
					<xs:complexType>
						<xs:attribute name="Radius" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="EndAngle" type="AttributeEquation" use="optional" />
						<xs:attribute name="StartAngle" type="AttributeEquation" use="optional" />
						<xs:attributeGroup ref="AttributeXY_" />
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Polygon">
					<xs:complexType>
						<xs:sequence>
							<xs:group ref="PointList_" />
						</xs:sequence>
						<xs:attribute name="FillColor" type="xs:string" use="optional" />
						<xs:attribute name="LineColor" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Image">
					<xs:complexType>
						<xs:sequence>
							<xs:choice minOccurs="0" maxOccurs="unbounded">
								<xs:element minOccurs="0" name="Transparent" type="xs:boolean" />
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string" />
					</xs:complexType>
				</xs:element>
				<xs:group minOccurs="0" maxOccurs="unbounded" ref="GaugeText_" />
				<xs:element minOccurs="0" maxOccurs="unbounded" name="Rectangle">
					<xs:complexType>
						<xs:attribute name="Width" type="AttributeEquation" />
						<xs:attribute name="Height" type="AttributeEquation" />
						<xs:attribute name="Corner" type="AttributeEquation" />
						<xs:attribute name="CornerStyle" type="CornerStyle_" />
						<xs:attributeGroup ref="AttributeXY_" />
						<xs:attributeGroup ref="AttributeStyle_" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:group>
	<xs:group name="KeyMap_">
		<xs:choice>
			<xs:element minOccurs="0" maxOccurs="1" name="KeyMap">
				<xs:complexType>
					<xs:group ref="Trigger_" />
				</xs:complexType>
			</xs:element>
			<xs:element minOccurs="0" maxOccurs="1" name="ActionMap">
				<xs:complexType>
					<xs:group ref="Trigger_" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="MouseArea_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="MouseArea">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:group ref="Position_" />
						<xs:group ref="Size_" />
						<xs:element minOccurs="1" maxOccurs="unbounded" name="MouseClick">
							<xs:complexType>
								<xs:sequence>
									<xs:choice>
										<xs:element minOccurs="0" name="KeyEvent" type="xs:string" />
										<xs:element name="Event" type="xs:string" />
									</xs:choice>
									<xs:group ref="Script_" />
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" use="optional" />
							</xs:complexType>
						</xs:element>
						<xs:group maxOccurs="1" ref="Visibility_" />
						<xs:group ref="MouseArea_" />
						<xs:group ref="Comment_" />
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Trigger_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="Trigger">
				<xs:complexType>
					<xs:sequence>
						<xs:choice>
							<xs:element name="KeyEvent" type="xs:string" />
							<xs:element name="Event" type="xs:string" />
						</xs:choice>
						<xs:element minOccurs="0" name="Script" type="Equation" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Position_">
		<xs:choice>
			<xs:element minOccurs="0" name="Position">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="Float2">
							<xs:attribute name="X" type="AttributeEquation" use="optional" />
							<xs:attribute name="Y" type="AttributeEquation" use="optional" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:choice>
				<xs:element minOccurs="0" name="FloatPosition" type="Float2" />
				<xs:element minOccurs="0" name="LeftScript" type="Equation" />
				<xs:element minOccurs="0" name="RightScript" type="Equation" />
			</xs:choice>
		</xs:choice>
	</xs:group>
	<xs:group name="Script_">
		<xs:sequence>
			<xs:element minOccurs="0" name="Script" type="Equation" />
		</xs:sequence>
	</xs:group>
	<xs:group name="Size_">
		<xs:choice>
			<xs:element minOccurs="0" name="Size">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="Float2" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="LineColor_">
		<xs:choice>
			<xs:element name="LineColor">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="Color_">
		<xs:choice>
			<xs:element name="Color">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string" />
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:group name="LineColorScript_">
		<xs:choice>
			<xs:element name="LineColorScript" type="Equation"/>
		</xs:choice>
	</xs:group>
	<xs:group name="Update_">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="Update">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:group ref="Script_" />
							<xs:element minOccurs="0" name="Frequency" type="xs:float" />
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Visibility_">
		<xs:choice>
			<xs:element minOccurs="0" name="Visible" type="Equation" />
			<xs:element minOccurs="0" name="Visibility" type="Equation" />
		</xs:choice>
	</xs:group>
	<xs:group name="Point_">
		<xs:sequence>
			<xs:element name="Point">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="Float2">
							<xs:attributeGroup ref="AttributeXY_" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="PointList_">
		<xs:sequence>
			<xs:group maxOccurs="unbounded" ref="Point_" />
		</xs:sequence>
	</xs:group>
	<xs:group name="ElementContent_">
		<xs:sequence>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:group ref="Element_" />
				<xs:group ref="Position_" />
				<xs:group ref="Graphic_" />
				<xs:group ref="Visibility_" />
				<xs:group ref="Select_" />
				<xs:group ref="Choose_" />
				<xs:group ref="ForLoop_" />
				<xs:group ref="Rotation_" />
				<xs:group ref="Include_" />
				<xs:group ref="Shift_" />
			</xs:choice>
		</xs:sequence>
	</xs:group>
	<xs:group name="Element_">
		<xs:sequence>
			<xs:element name="Element">
				<xs:complexType>
					<xs:group ref="ElementContent_" />
					<xs:attribute name="id" type="xs:string" />
					<xs:attribute name="Context" type="Context_" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Expression_">
		<xs:sequence>
			<xs:element name="Expression">
				<xs:complexType>
					<xs:all>
						<xs:element minOccurs="0" maxOccurs="1" name="Minimum" type="xs:float" />
						<xs:element minOccurs="0" maxOccurs="1" name="Maximum" type="xs:float" />
						<xs:element minOccurs="1" maxOccurs="1" name="Script" type="Equation" />
					</xs:all>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Select_">
		<xs:sequence>
			<xs:element name="Select">
				<xs:complexType>
					<xs:sequence>
						<xs:group maxOccurs="1" ref="Expression_" />
						<xs:element minOccurs="1" maxOccurs="unbounded" name="Case">
							<xs:complexType>
								<xs:sequence>
									<xs:choice>
										<xs:element name="ExpressionResult" type="xs:string" />
										<xs:group ref="Expression_" />
									</xs:choice>
									<xs:group ref="ElementContent_" />
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" />
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" maxOccurs="1" name="CaseElse">
							<xs:complexType>
								<xs:group ref="ElementContent_" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Choose_">
		<xs:sequence>
			<xs:element name="Choose">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="1" maxOccurs="unbounded" name="When">
							<xs:complexType>
								<xs:sequence>
									<xs:choice>
										<xs:group ref="Expression_" />
									</xs:choice>
									<xs:group ref="ElementContent_" />
								</xs:sequence>
								<xs:attribute name="id" type="xs:string" />
							</xs:complexType>
						</xs:element>
						<xs:element minOccurs="0" maxOccurs="1" name="Otherwise">
							<xs:complexType>
								<xs:group ref="ElementContent_" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="ForLoop_">
		<xs:sequence>
			<xs:element name="ForLoop">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="InitialExpression">
							<xs:complexType>
								<xs:group ref="Script_" />
							</xs:complexType>
						</xs:element>
						<xs:element name="TestExpression">
							<xs:complexType>
								<xs:group ref="Script_" />
							</xs:complexType>
						</xs:element>
						<xs:element name="IncrementExpression">
							<xs:complexType>
								<xs:group ref="Script_" />
							</xs:complexType>
						</xs:element>
						<xs:group ref="ElementContent_" />
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Value_">
		<xs:sequence>
			<xs:element name="Value" type="xs:string" />
		</xs:sequence>
	</xs:group>
	<xs:group name="GaugeText_">
		<xs:sequence>
			<xs:element name="GaugeText">
				<xs:complexType>
					<xs:sequence>
						<xs:element minOccurs="1" maxOccurs="unbounded" name="String" type="xs:string" />
					</xs:sequence>
					<xs:attribute name="X" type="AttributeEquation" />
					<xs:attribute name="Y" type="AttributeEquation" />
					<xs:attribute name="Align" type="TextAlign_" />
					<xs:attribute name="VerticalAlign" type="TextVerticalAlign_" />
					<xs:attribute name="Font" type="xs:string" />
					<xs:attribute name="Height" type="xs:float" />
					<xs:attribute name="LineColor" type="AttributeEquation" />
					<xs:attribute name="Color" type="AttributeEquation" />
					<xs:attribute name="HaloColor" type="AttributeEquation" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:simpleType name="TextAlign_">
		<xs:restriction base="xs:string">
			<xs:enumeration value="center" />
			<xs:enumeration value="left" />
			<xs:enumeration value="right" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TextVerticalAlign_">
		<xs:restriction base="xs:string">
			<xs:enumeration value="top" />
			<xs:enumeration value="middle" />
			<xs:enumeration value="center" />
			<xs:enumeration value="baseline" />
			<xs:enumeration value="bottom" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Context_" >
		<xs:restriction base="xs:string">
			<xs:enumeration value="group" />
			<xs:enumeration value="foreground" />
			<xs:enumeration value="background" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CornerStyle_">
		<xs:restriction base="xs:string">
			<xs:enumeration value="square" />
			<xs:enumeration value="bevel" />
			<xs:enumeration value="round" />
		</xs:restriction>
	</xs:simpleType>
	<xs:group name="Rotation_">
		<xs:sequence>
			<xs:element name="Rotation" type="Equation" />
		</xs:sequence>
	</xs:group>
	<xs:group name="Include_">
		<xs:sequence>
			<xs:element name="Include">
				<xs:complexType>
					<xs:attribute name="File" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="Shift_">
		<xs:sequence>
			<xs:element name="Shift">
				<xs:complexType>
					<xs:attributeGroup ref="AttributeXY_" />
					<xs:attribute name="Maximum" type="AttributeEquation" />
					<xs:attribute name="Minimum" type="AttributeEquation" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
</xs:schema>

=== grizzie17/GS8/Config/gauges/view-select.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="view-select">
		<ActionMap>
			<Trigger>
				<KeyEvent>E:Change Layout</KeyEvent>
				<Script>(E:Change Layout) (=U:View Layout)</Script>
			</Trigger>
		</ActionMap>
		<Element Context="background">
			<Select>
				<Expression>
					<Script>(U:View Layout)</Script>
				</Expression>
				<Case>
					<Expression>
						<Script>(K:View Forward)</Script>
					</Expression>
					<Include File="view-select-forward"/>
				</Case>
				<Case>
					<Expression>
						<Script>(K:View Reverse)</Script>
					</Expression>
					<Include File="view-select-reverse"/>
				</Case>
				<Case>
					<Expression>
						<Script>(K:View Single)</Script>
					</Expression>
					<Include File="view-select-single"/>
				</Case>
				<Case>
					<Expression>
						<Script>(K:View Single Auto)</Script>
					</Expression>
					<Include File="view-select-single-auto"/>
				</Case>
				<Case>
					<Expression>
						<Script>(K:View Quad)</Script>
					</Expression>
					<Include File="view-select-quad"/>
				</Case>
			</Select>
		</Element>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/icon-sharpness.xml
<?xml version="1.0"?>
<Gauge Name="icon-sharpness" Version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<Size>70,45</Size>
	<Element Context="background">
		<!--
			All icon files utlize the registers to pass color information. The current register assignment is as follows:
			r0 defines the visiblity of the icon
			r1..r5 defines the color palet (It is not required to utlize all of the registers)
			-->
		<Visible>r0</Visible>
		<Circle X="20" Y="22" Radius="20" LineColor="r1" LineWidth="2"/>
		<Line Color="r1" LineWidth="1">
			<Point X="20" Y="2"/>
			<Point X="20" Y="42"/>
		</Line>
		<Line Color="r1" LineWidth="1">
			<Point X="0" Y="22"/>
			<Point X="40" Y="22"/>
		</Line>
	</Element>
</Gauge>

=== grizzie17/GS8/Config/gauges/button-units.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="button-units">
		<Update>
			<Script>
				// Define the button text
				"Units" s6
				'Metric' 'English' 2 (U:UNITS) case s7 both
				" " s8 both

				// Define the button text colors
				(U:COLOR_ButtonText) s1 both
				r1 s2 both
				r1 s3 both

				(U:BLACKOUT SELECTED) ! s0 both
			</Script>
		</Update>
		<Size>70,60</Size>
		<Element>
			<Include File="icon-text" />
		</Element>
		<MouseArea id="MouseArea">
			<FloatPosition>0.000,0.000</FloatPosition>
			<Size>70,60</Size>
			<MouseClick id="MouseClick">
				<KeyEvent>E:TOGGLE UNITS</KeyEvent>
			</MouseClick>
		</MouseArea>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/proprietary.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="proprietary">
		<Size>120,64</Size>
		<Element Context="background">
			<GaugeText X="0" Y="0"
					   Font="sans-serif" Height="16"
					   VerticalAlign="top"
					   Color="white">
				<String>This data or other information is proprietary to and a confidential trade secret of DRS TEM. It should not be</String>
			</GaugeText>
			<GaugeText X="0" Y="16"
					   Font="sans-serif" Height="16"
					   VerticalAlign="top"
					   Color="white">
				<String>revealed or disclosed to anyone outside of the U.S. Government or the company to which it was initially</String>
			</GaugeText>
			<GaugeText X="0" Y="32"
					   Font="sans-serif" Height="16"
					   VerticalAlign="top"
					   Color="white">
				<String>sent for any purpose under authority of the third and fourth exemptions to the Freedom of Information Act,</String>
			</GaugeText>
			<GaugeText X="0" Y="48"
					   Font="sans-serif" Height="16"
					   VerticalAlign="top"
					   Color="white">
				<String>Trade Secrets Act, and the Administration Procedure Act.</String>
			</GaugeText>
		</Element>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/gaugestogglenotice.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge>
		<Update>
			<Frequency>4</Frequency>
			<Script>
				/*
					If the gauge switch has changed state from last update then
						(=G:Timeout) += 3000
					else
						do nothing
				*/
					(S:MILLI) 3000 +
					(G:Timeout)
				(U:GAUGE SWITCH) (G:Last Setting) != ?	(=G:Timeout)
				
				/* Save the current guage switch state for next update cycle. */
				(U:GAUGE SWITCH) (=G:Last Setting)
				both
			</Script>
		</Update>
		<Element>
		<!--
			If the guage switch has updated within the last 3000 mS, then display the state
			The possible states are stored in (G:Last Setting). This variable is set by pressing <F5>. See "driver.xml".
				0 - Gauge Auto
				1 - Gauge On
				2 - Gauge Off
		-->
		<Visibility> (S:MILLI) (G:Timeout) &lt;</Visibility>
			<Select>
				<Expression>
					<Script>(G:Last Setting)</Script>
				</Expression>
				<Case>
					<ExpressionResult>0</ExpressionResult>
					<GaugeText Y="0" X="0" Font="Arial" Height="24" Align="left" VerticalAlign="top" LineColor="lightgreen">
						<String>Gauge Auto</String>
					</GaugeText>
				</Case>
				<Case>
					<ExpressionResult>1</ExpressionResult>
					<GaugeText Y="0" X="0" Font="Arial" Height="24" Align="left" VerticalAlign="top" LineColor="lightgreen">
						<String>Gauge ON</String>
					</GaugeText>
				</Case>
				<Case>
					<ExpressionResult>2</ExpressionResult>
					<GaugeText Y="0" X="0" Font="Arial" Height="24" Align="left" VerticalAlign="top" LineColor="lightgreen">
						<String>Gauge OFF</String>
					</GaugeText>
				</Case>
				<CaseElse>
					<GaugeText Y="0" X="0" Font="Arial" Height="24" Align="left" VerticalAlign="top" LineColor="lightgreen">
						<String>???</String>
					</GaugeText>
				</CaseElse>

			</Select>
		</Element>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/dial-speed.xml
<?xml version="1.0" ?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="dial-speed">
		<Update>
			<!-- 
			r0 =	starting angle
			r1 =	total sweep angle (clockwise)
			r2 =	numbers for dial
			r3 =	current angle
			r5 =	sweep value for #10
			r6 =	normalized value of #10
			r7 =	normalized current value (range: 0-1)
			r8 =	high value
			r9 =	current value
			-->
			<Script>
				180 1.25 * s0		// start angle
				180 1.5 * s1 both	// sweep
				
				/* sample comment */

				(A:Vehicle Speed,km/h) (A:Vehicle Speed,mph) 2 (U:UNITS) case s9 both
				(B:Vehicle Speed.High,km/h) (B:Vehicle Speed.High,mph) 2 (U:UNITS) case s8 both
				r9 r8 / s7 both

			</Script>
		</Update>
		<Size>280,280</Size>
		<Element Context="group">
			<Position X="140" Y="140" />
			<Element Context="background">
				<Circle X="0" Y="0" Radius="140" FillColor="charcoal" />
				<Circle X="2" Y="2" Radius="137" LineWidth="4" LineColor="black" />
				<Circle X="0" Y="0" Radius="137" LineWidth="4" LineColor="darkgray" />
				<Select>
					<Expression>
						<Script>(U:UNITS)</Script>
					</Expression>
					<Case>
						<ExpressionResult>0</ExpressionResult>
						<GaugeText X="0" Y="40"
								   Font="sans-serif" Height="18" Color="white"
								   Align="center" VerticalAlign="top">
							<String>M.P.H.</String>
						</GaugeText>
					</Case>
					<Case>
						<ExpressionResult>1</ExpressionResult>
						<GaugeText X="0" Y="40"
								   Font="sans-serif" Height="18" Color="white"
								   Align="center" VerticalAlign="top">
							<String>km/h</String>
						</GaugeText>
					</Case>
				</Select>
				<Element>
					<ForLoop>
						<InitialExpression>
							<Script>
								180 1.25 * s0
								180 1.5 * s1 both
								0 s2 both
								0.0 s3 both

								(A:Vehicle Speed,km/h) (A:Vehicle Speed,mph) 2 (U:UNITS) case s9 both
								(B:Vehicle Speed.High,km/h) (B:Vehicle Speed.High,mph) 2 (U:UNITS) case s8 both
								5.0 r8 / r1 * s5 both
							</Script>
						</InitialExpression>
						<TestExpression>
							<Script>
								r3 r1 &lt;=
							</Script>
						</TestExpression>
						<IncrementExpression>
							<Script>
								r2 10 + s2
								r3 r5 + s3 both
							</Script>
						</IncrementExpression>
						<Rotation>r0 r3 -</Rotation>
						<Line LineColor="lightgray" LineWidth="1">
							<Point X="130" Y="0" />
							<Point X="122" Y="0" />
						</Line>
					</ForLoop>
					<ForLoop>
						<InitialExpression>
							<Script>
								180 1.25 * s0
								180 1.5 * s1 both
								0 s2 both
								0.0 s3 both

								(A:Vehicle Speed,km/h) (A:Vehicle Speed,mph) 2 (U:UNITS) case s9 both
								(B:Vehicle Speed.High,km/h) (B:Vehicle Speed.High,mph) 2 (U:UNITS) case s8 both
								10.0 r8 / r1 * s5 both
							</Script>
						</InitialExpression>
						<TestExpression>
							<Script>
								r3 r1 &lt;=
							</Script>
						</TestExpression>
						<IncrementExpression>
							<Script>
								r2 10 + s2
								r3 r5 + s3 both
							</Script>
						</IncrementExpression>
						<Rotation>r0 r3 -</Rotation>
						<Line LineColor="white" LineWidth="3">
							<Point X="132" Y="0" />
							<Point X="120" Y="0" />
						</Line>
						<Choose>
							<When>
								<Expression>
									<!--
									r8 < 120  ||  0 == (r2 % 20)
									-->
									<Script>
										r8 120 &lt;
										r2 20 % 0 ==
										||
									</Script>
								</Expression>
								<GaugeText X="100" Y="0"
										   Font="sans-serif" Height="26"
										   Color="white"
										   Align="center" VerticalAlign="middle">
									<String>%(r2)%!d!</String>
								</GaugeText>
							</When>
						</Choose>
					</ForLoop>
				</Element>
			</Element>
			<Element Context="foreground">
				<Element>
					<Rotation>r0 r7 r1 * - s5</Rotation>
					<Position X="6" Y="6" />
					<Polygon FillColor="black">
						<Point X="-30" Y="-3" />
						<Point X="118" Y="-1" />
						<Point X="120" Y="0" />
						<Point X="118" Y="1" />
						<Point X="-30" Y="3" />
						<Point X="-30" Y="-3" />
					</Polygon>
				</Element>
				<Circle X="6" Y="6"
						Radius="15" FillColor="black"
						LineColor="black" LineWidth="2" />
				<Element>
					<Rotation>r5</Rotation>
					<Polygon FillColor="red" LineColor="crimson">
						<Point X="-30" Y="-3" />
						<Point X="118" Y="-1" />
						<Point X="120" Y="0" />
						<Point X="118" Y="1" />
						<Point X="-30" Y="3" />
						<Point X="-30" Y="-3" />
					</Polygon>
				</Element>
				<Circle X="0" Y="0"
						Radius="15" FillColor="gray"
						LineColor="silver" LineWidth="2" />


			</Element>
		</Element>
	</SimGauge.Gauge>
</SimBase.Document>

=== grizzie17/GS8/Config/gauges/LAV3-button-camera-feed.xml
<?xml version="1.0"?>
<SimBase.Document Type="AceXML" version="1,0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Gauges.xsd">
	<SimGauge.Gauge id="LAV3-button-camera-feed">
		<Size>70,60</Size>
		<Update>
			<!-- s1 defines the icon color -->
			<Script>
        // Define the 3 lines of text on the button
        "Change" s6
        "Camera" s7
        both
        " " s8
        both

        // Each of the 3 lines of texts may have its own color
        0x00FF00 s1
        both
        r1 s2
        both
        r1 s3
        both

        // Make sure the arrows are also hidden if the button is hidden.
        " " 0 (=U:CAMERA SELECT ACTIVE)
        (U:View Layout) (K:View PIP) == (U:View Layout) (K:View Quad) == (U:View Layout) (K:View Single) == OR OR ?
        both

        (U:View Layout) (K:View PIP) == (U:View Layout) (K:View Quad) == (U:View Layout) (K:View Single) == OR OR s0
        both
      </Script>
		</Update>
		<Element>
			<Include File="icon-text" />
		</Element>
		<MouseArea id="MouseArea">
			<FloatPosition>0.000,0.000</FloatPosition>
			<Size>70,60</Size>
			<MouseClick id="MouseClick">
				<KeyEvent>E:CAMERA SELECT</KeyEvent>
			</MouseClick>
		</MouseArea>
	</SimGauge.Gauge>
</SimBase.Document>
