=== grizzie17/GS8/Config/dictionary/configuration.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified" 
		   elementFormDefault="qualified" 
		   xmlns:xs="http://www.w3.org/2001/XMLSchema">



	<!-- 
	###########################################################
	||	Types
	###########################################################
	-->

	
	<!-- enumerations -->

	<xs:simpleType name="enumType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BOOLEAN" />
			<xs:enumeration value="COLOR" />
			<xs:enumeration value="DATETIME" />
			<xs:enumeration value="ENUM" />
			<xs:enumeration value="FLOAT" />
			<xs:enumeration value="INTEGER" />
			<xs:enumeration value="STRING" />
		</xs:restriction>
	</xs:simpleType>






	<xs:element name="Configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Item" />
					<xs:element ref="Include" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>



	<xs:element name="Item">
		<xs:complexType mixed="true">
			<xs:attribute name="ID" type="xs:string" use="required" />
			<xs:attribute name="Type" type="enumType" use="required" />
			<xs:attribute name="Units" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>


	<xs:element name="Include">
		<xs:complexType>
			<xs:attribute name="File" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	











</xs:schema>

=== grizzie17/GS8/Config/dictionary/TEST_configuration1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Configuration information -->
<Configuration 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="configuration.xsd">
	
	<Include File="ESAV_config_commander"/>
	
  <Item ID="Display" Type="STRING">Driver Position 1</Item>
  <Item ID="Device ID" Type="INTEGER" >26</Item>
  <Item ID="Monitor Type" Type="STRING">UkCtd_13</Item>
  <Item ID="Input Devices" Type="STRING">ukctd13_input_device</Item>
  <Item ID="Network Port" Type="INTEGER" >1556</Item>
  <Item ID="DSP IP Address" Type="STRING">192.168.0.207</Item>
  <Item ID="DSP IP Port" Type="INTEGER">5389</Item>
</Configuration>

=== grizzie17/GS8/Config/dictionary/LAV3_configuration3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Configuration information -->
<Configuration
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="configuration.xsd">

	<Include File="LAV3_config_gauges"/>

   <Item ID="Display" Type="STRING">Commander Position 2</Item>
   <Item ID="Device ID" Type="INTEGER" >28</Item>
   <Item ID="Monitor Type" Type="STRING">GDC_SDU16_1_1280x768_60Hz</Item>
   <Item ID="Input Devices" Type="STRING">LAV3_input_devices_3</Item>
   <Item ID="Network Port" Type="INTEGER" >1553</Item>
   <Item ID="DSP IP Address" Type="STRING">192.168.1.209</Item>
   <Item ID="DSP IP Port" Type="INTEGER">5389</Item>

</Configuration>
