=== grizzie17/GS8/Config/plugins/plugin.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified"
		   elementFormDefault="qualified"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema">



	<!--
	###########################################################
	||	Types
	###########################################################
	-->


	<!-- enumerations -->

	<xs:simpleType name="enumType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BOOLEAN" />
			<xs:enumeration value="COLOR" />
			<xs:enumeration value="DATETIME" />
			<xs:enumeration value="ENUM" />
			<xs:enumeration value="FLOAT" />
			<xs:enumeration value="INTEGER" />
			<xs:enumeration value="STRING" />
		</xs:restriction>
	</xs:simpleType>


	<xs:element name="Plugins">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Plugin" />
					<xs:element ref="Include" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="Group" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>


	<xs:element name="PluginInclude">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Parameters" />
					<xs:element ref="Plugin" />
					<xs:element ref="Include" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>



	<xs:element name="Plugin">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Param" />
					<xs:element ref="Plugin" />
					<xs:element ref="Include" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="Class" type="xs:string" use="required" />
			<xs:attribute name="ID" type="xs:string" use="optional" />
			<xs:attribute name="Group" type="xs:string" use="optional" />
			<xs:attribute name="Filter" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>


	<xs:element name="Parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Param" />
					<xs:element ref="Plugin" />
					<xs:element ref="Include" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>









	<xs:element name="Param">
		<xs:complexType mixed="true">
			<xs:attribute name="Name" type="xs:string" use="required" />
			<xs:attribute name="Type" type="enumType" use="required" />
			<xs:attribute name="Units" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>


	<xs:element name="Include">
		<xs:complexType>
			<xs:attribute name="File" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>













</xs:schema>

=== grizzie17/GS8/Config/plugins/inputdevices/ukctd_input_devices_0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Plugin information -->
<Plugins Group=""
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../plugin.xsd">
	<Plugin Class="InputUkCdtVDDS" ID="VCB 0">
		<!-- Avalex touch screen input device -->
		<Plugin Class="CommSerialVDDS" ID="RS-232 0">
			<!--IDataStream plugin -->
			<Param Name="Port" Type="STRING">/dev/ttyVDDS0</Param>
			<Param Name="Baud" Type="INTEGER">9600</Param>
			<Param Name="Parity" Type="STRING">None</Param>
			<Param Name="Stop Bits" Type="INTEGER">1</Param>
			<Param Name="Data Bits" Type="INTEGER">8</Param>
			<Param Name="Flow Control" Type="STRING">None</Param>
		</Plugin>
		<Plugin Class="MsgVcb" ID="Vcb Msg 0">
			<!--IDataLink plugin -->
		</Plugin>
		<Plugin Class="EventGraphicsVDDS" ID="Graphic Events 0">
			<!--IGraphicsEvent plugin -->
		</Plugin>
		<Plugin Class="CmdVcb" ID="Menu Light 0">
			<!--CmdVcb plugin -->
		</Plugin>
	</Plugin>
</Plugins>

=== grizzie17/GS8/Config/plugins/inputdevices/serial_pass_thru_bi_directional.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Plugin information -->
<Plugins Group=""
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../plugin.xsd">

  <!-- Pass through inputs between 2 serial devices
       Inputs from the Controller Module (CM) are passed to the 
       Electronic Pand and Tilt Module (EPTM)
       
       Inputs from the EPTM are passed to the CM-->

  <Plugin Class="InputSerialPassThruBiDirectionalVDDS" ID="CM - EPTM">

    <Plugin Class="CommSerialPassThruBiDirectional" ID="RS485">
        <!-- CM  - 485 serial port configuration-->
        <Param Name="Port1" Type="STRING">/dev/ttyVDDS4852</Param>
        <Param Name="Baud1" Type="INTEGER">19200</Param>
        <Param Name="Parity1" Type="STRING">None</Param>
        <Param Name="Stop Bits1" Type="INTEGER">1</Param>
        <Param Name="Data Bits1" Type="INTEGER">8</Param>
        <Param Name="Flow Control1" Type="STRING">None</Param>

        <!-- EPTM - 485 serial port configuration -->
        <Param Name="Port2" Type="STRING">/dev/ttyVDDS4850</Param>
        <Param Name="Baud2" Type="INTEGER">19200</Param>
        <Param Name="Parity2" Type="STRING">None</Param>
        <Param Name="Stop Bits2" Type="INTEGER">1</Param>
        <Param Name="Data Bits2" Type="INTEGER">8</Param>
        <Param Name="Flow Control2" Type="STRING">None</Param>
    </Plugin>
  </Plugin>
</Plugins>

=== grizzie17/GS8/Config/plugins/services/MO_sspc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Task Plugins -->
<Plugins Group="" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="../plugin.xsd">



	<Include File="VehicleDataSample"/>

	<Plugin Class="ServiceRstaEptm" ID="Service EPTM">
		<Param Name="EPTM::Port" Type="STRING">/dev/ttyVDDS4853</Param>
		<Param Name="EPTM::Baud" Type="INTEGER">19200</Param>
		<Param Name="EPTM::Parity" Type="STRING">None</Param>
		<Param Name="EPTM::StopBits" Type="INTEGER">1</Param>
		<Param Name="EPTM::DataBits" Type="INTEGER">8</Param>
		<Param Name="EPTM::Flow" Type="STRING">None</Param>

		<!-- EPTM - 485 serial port configuration -->
		<Param Name="CMM::Port" Type="STRING">/dev/ttyVDDS4850</Param>
		<Param Name="CMM::Baud" Type="INTEGER">19200</Param>
		<Param Name="CMM::Parity" Type="STRING">None</Param>
		<Param Name="CMM::StopBits" Type="INTEGER">1</Param>
		<Param Name="CMM::DataBits" Type="INTEGER">8</Param>
		<Param Name="CMM::Flow" Type="STRING">None</Param>

		<Param Name="Auto Pan Row Spacing" Type="FLOAT">15.0</Param>
	</Plugin>

</Plugins>
