=== grizzie17/GS8/Config/plugins/plugin.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified"
		   elementFormDefault="qualified"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema">



	<!--
	###########################################################
	||	Types
	###########################################################
	-->


	<!-- enumerations -->

	<xs:simpleType name="enumType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BOOLEAN" />
			<xs:enumeration value="COLOR" />
			<xs:enumeration value="DATETIME" />
			<xs:enumeration value="ENUM" />
			<xs:enumeration value="FLOAT" />
			<xs:enumeration value="INTEGER" />
			<xs:enumeration value="STRING" />
		</xs:restriction>
	</xs:simpleType>


	<xs:element name="Plugins">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Plugin" />
					<xs:element ref="Include" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="Group" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>


	<xs:element name="PluginInclude">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Parameters" />
					<xs:element ref="Plugin" />
					<xs:element ref="Include" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>



	<xs:element name="Plugin">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Param" />
					<xs:element ref="Plugin" />
					<xs:element ref="Include" />
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="Class" type="xs:string" use="required" />
			<xs:attribute name="ID" type="xs:string" use="optional" />
			<xs:attribute name="Group" type="xs:string" use="optional" />
			<xs:attribute name="Filter" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>


	<xs:element name="Parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="Param" />
					<xs:element ref="Plugin" />
					<xs:element ref="Include" />
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>









	<xs:element name="Param">
		<xs:complexType mixed="true">
			<xs:attribute name="Name" type="xs:string" use="required" />
			<xs:attribute name="Type" type="enumType" use="required" />
			<xs:attribute name="Units" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>


	<xs:element name="Include">
		<xs:complexType>
			<xs:attribute name="File" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>













</xs:schema>

=== grizzie17/GS8/Config/plugins/monitors/NTSC_Generic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Avalex Display Configuration -->
<Plugins Group=""
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../plugin.xsd">
	<Plugin Class="MonGeneric">
		<Param Name="Name" Type="STRING">GENERIC</Param>	<!-- Legacy entry that is not utilized at this time -->
		<Param Name="Description" Type="STRING">Standard NTSC Composite Monitor</Param>	<!-- Legacy entry that is not utilized at this time -->
		<Param Name="Display Profile" Type="ENUM">DIS_NTSC_CUSTOM</Param>
		<Param Name="Commanded State" Type="INTEGER">0</Param>	<!-- Legacy entry that is not utilized at this time -->
		<Param Name="Horizontal Numerator" Type="INTEGER">1</Param>	<!-- Legacy entry that is not utilized at this time -->
		<Param Name="Horizontal Denominator" Type="INTEGER">1</Param>	<!-- Legacy entry that is not utilized at this time -->
		<Param Name="Vertical Numerator" Type="INTEGER">1</Param>	<!-- Legacy entry that is not utilized at this time -->
		<Param Name="Vertical Denominator" Type="INTEGER">1</Param>	<!-- Legacy entry that is not utilized at this time -->
		<Param Name="Width" Type="INTEGER">720</Param>
		<Param Name="Height" Type="INTEGER">480</Param>
		<Param Name="D Mode" Type="ENUM">VPORT_MODE_BT656_8BIT</Param>	<!-- #define VPORT_MODE_BT656_8BIT		0x00000000 -->
		<Param Name="Fld Op" Type="ENUM">VPORT_FLDOP_FRAME</Param>		<!-- #define VPORT_FLDOP_FRAME			0x00000004 -->
		<Param Name="Frm HSize" Type="INTEGER">858</Param>
		<Param Name="Frm VSize" Type="INTEGER">525</Param>
		<Param Name="Img HOffset Fld 1" Type="INTEGER">0</Param>
		<Param Name="Img VOffset Fld 1" Type="INTEGER">0</Param>
		<Param Name="Img HSize Fld 1" Type="INTEGER">720</Param>
		<Param Name="Img VSize Fld 1" Type="INTEGER">240</Param>
		<Param Name="Img HOffset Fld 2" Type="INTEGER">0</Param>
		<Param Name="Img VOffset Fld 2" Type="INTEGER">0</Param>
		<Param Name="Img HSize Fld 2" Type="INTEGER">720</Param>
		<Param Name="Img VSize Fld 2" Type="INTEGER">240</Param>
		<Param Name="H Blnk Start" Type="INTEGER">720</Param>
		<Param Name="H Blnk Stop" Type="INTEGER">856</Param>
		<Param Name="V Blnk X Start Fld 1" Type="INTEGER">720</Param>
		<Param Name="V Blnk Y Start Fld 1" Type="INTEGER">1</Param>
		<Param Name="V Blnk X Stop Fld 1" Type="INTEGER">720</Param>
		<Param Name="V Blnk Y Stop Fld 1" Type="INTEGER">21</Param>
		<Param Name="V Blnk X Start Fld 2" Type="INTEGER">360</Param>
		<Param Name="V Blnk Y Start Fld 2" Type="INTEGER">263</Param>
		<Param Name="V Blnk X Stop Fld 2" Type="INTEGER">360</Param>
		<Param Name="V Blnk Y Stop Fld 2" Type="INTEGER">284</Param>
		<Param Name="X Start Fld 1" Type="INTEGER">720</Param>
		<Param Name="Y Start Fld 1" Type="INTEGER">1</Param>
		<Param Name="X Start Fld 2" Type="INTEGER">360</Param>
		<Param Name="Y Start Fld 2" Type="INTEGER">263</Param>
		<Param Name="H Sync Start" Type="INTEGER">736</Param>
		<Param Name="H Sync Stop" Type="INTEGER">800</Param>
		<Param Name="V Sync X Start Fld 1" Type="INTEGER">736</Param>
		<Param Name="V Sync Y Start Fld 1" Type="INTEGER">4</Param>
		<Param Name="V Sync X Stop Fld 1" Type="INTEGER">736</Param>
		<Param Name="V Sync Y Stop Fld 1" Type="INTEGER">7</Param>
		<Param Name="V Sync X Start Fld 2" Type="INTEGER">307</Param>
		<Param Name="V Sync Y Start Fld 2" Type="INTEGER">266</Param>
		<Param Name="V Sync X Stop Fld 2" Type="INTEGER">307</Param>
		<Param Name="V Sync Y Stop Fld 2" Type="INTEGER">269</Param>
	</Plugin>
</Plugins>

=== grizzie17/GS8/Config/plugins/videosources/ESAV_video_sources.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Plugin information -->
<Plugins Group=""
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../plugin.xsd">


	<!--

      here are the video source ESAV supports
      Camera Front  - In7 - 0
      Camera Left   - In2 - 1
      Camera Right  - In3(8) - 2
      Camera Rear IR - In1 - 4
      Camera Rear Color - In10 - 5
       Camera DVD Player - In6 - 3
      Camera DCM Text   - In17 - 6
      Camera Observer   - In4(3) - 7      
	-->



	<Plugin Class="VideoSourceAggregate" ID="Camera Front">
		<Param Name="Server ID" Type="INTEGER">0</Param>
		<Param Name="Icon" Type="STRING">camera_frontcenter</Param>
		<Plugin Class="VideoSourceAnalogVdds" Filter="Client" ID="Analog Camera 0">
			<Include File="NTSC_GENERIC_Frame"/>
			<!--
			RGB1 In7
			-->
			<Param Name="Video Input Port" Type="INTEGER">7</Param>
		</Plugin>
		<Plugin Class="CmdCameraSelector">
			<Param Name="Up" Type="STRING">Camera Rear Color</Param>
			<Param Name="Down" Type="STRING">Camera Rear IR</Param>
			<Param Name="Left" Type="STRING">Camera Left</Param>
			<Param Name="Right" Type="STRING">Camera Right</Param>
		</Plugin>
	</Plugin>



	<Plugin Class="VideoSourceAggregate" ID="Camera Left">
		<Param Name="Server ID" Type="INTEGER">1</Param>
		<Param Name="Icon" Type="STRING">camera_frontleft</Param>
		<Plugin Class="VideoSourceAnalogVdds" Filter="Client" ID="Analog Camera 1">
			<!--
			RS170 In2
			-->
			<Include File="NTSC_GENERIC_Frame"/>
			<Param Name="Video Input Port" Type="INTEGER">2</Param>
		</Plugin>
		<Plugin Class="CmdCameraSelector">
			<Param Name="Up" Type="STRING">Camera Front</Param>
			<Param Name="Down" Type="STRING">Camera DVD Player</Param>
			<Param Name="Left" Type="STRING">Camera Left</Param>
			<Param Name="Right" Type="STRING">Camera Right</Param>
		</Plugin>
	</Plugin>



	<Plugin Class="VideoSourceAggregate" ID="Camera Right">
		<Param Name="Server ID" Type="INTEGER">2</Param>
		<Param Name="Icon" Type="STRING">camera_frontright</Param>
		<Plugin Class="VideoSourceAnalogVdds" Filter="Client" ID="Analog Camera 2">
			<!--
			RS170 In3
			-->
			<Include File="NTSC_GENERIC_Frame"/>
			<Param Name="Video Input Port" Type="INTEGER">8</Param>
		</Plugin>
		<Plugin Class="CmdCameraSelector">
			<Param Name="Up" Type="STRING">Camera Front</Param>
			<Param Name="Down" Type="STRING">Camera Rear Color</Param>
			<Param Name="Left" Type="STRING">Camera Left</Param>
			<Param Name="Right" Type="STRING">Camera DVD Player</Param>
		</Plugin>
	</Plugin>

	<Plugin Class="VideoSourceAggregate" ID="Camera DVD Player">
		<Param Name="Server ID" Type="INTEGER">3</Param>
		<Param Name="Icon" Type="STRING">camera_dvd</Param>
		<Plugin Class="VideoSourceAnalogVdds" Filter="Client" ID="Analog Camera 3">
			<!--
			RS170 In6
			-->
			<Include File="NTSC_GENERIC_Frame"/>
			<Param Name="Video Input Port" Type="INTEGER">6</Param>
		</Plugin>
		<Plugin Class="CmdCameraSelector">
			<Param Name="Up" Type="STRING">Camera Front</Param>
			<Param Name="Down" Type="STRING">Camera Rear Color</Param>
			<Param Name="Left" Type="STRING">Camera Left</Param>
			<Param Name="Right" Type="STRING">Camera DVD Player</Param>
		</Plugin>
	</Plugin>



	<Plugin Class="VideoSourceAggregate" ID="Camera Rear IR">
		<Param Name="Server ID" Type="INTEGER">4</Param>
		<Param Name="Icon" Type="STRING">camera_rear</Param>
		<Plugin Class="VideoSourceAnalogVdds" Filter="Client" ID="Analog Camera 4">
			<!--
			RS170 In1
			-->
			<Include File="NTSC_GENERIC_Frame"/>
			<Param Name="Video Input Port" Type="INTEGER">1</Param>
		</Plugin>
		<Plugin Class="CmdCameraSelector">
			<Param Name="Up" Type="STRING">Camera Front</Param>
			<Param Name="Down" Type="STRING">Camera Rear Color</Param>
			<Param Name="Left" Type="STRING">Camera Left</Param>
			<Param Name="Right" Type="STRING">Camera DVD Player</Param>
		</Plugin>
	</Plugin>



	<Plugin Class="VideoSourceAggregate" ID="Camera Rear Color">
		<Param Name="Server ID" Type="INTEGER">5</Param>
		<Param Name="Icon" Type="STRING">camera_rear</Param>
		<Plugin Class="VideoSourceAnalogVdds" Filter="Client" ID="Analog Camera 5">
			<!--
			RS170 In10
			-->
			<Include File="NTSC_GENERIC_Frame"/>
			<Param Name="Video Input Port" Type="INTEGER">10</Param>
		</Plugin>
		<Plugin Class="CmdCameraSelector">
			<Param Name="Up" Type="STRING">Camera Front</Param>
			<Param Name="Down" Type="STRING">Camera Rear Color</Param>
			<Param Name="Left" Type="STRING">Camera Left</Param>
			<Param Name="Right" Type="STRING">Camera DVD Player</Param>
		</Plugin>
	</Plugin>



	<Plugin Class="VideoSourceAggregate" ID="Camera DCM Text">
		<Param Name="Server ID" Type="INTEGER">6</Param>
		<Param Name="Icon" Type="STRING">camera_pc</Param>
		<Plugin Class="VideoSourceAnalogVdds" Filter="Client" ID="Analog Camera 6">
			<!--
			RS170 In5
			-->
			<Include File="RGB_XGA_60Hz"/>
			<Param Name="Video Input Port" Type="INTEGER">17</Param>
		</Plugin>
		<Plugin Class="CmdCameraSelector">
			<Param Name="Up" Type="STRING">Camera Front</Param>
			<Param Name="Down" Type="STRING">Camera Rear Color</Param>
			<Param Name="Left" Type="STRING">Camera Left</Param>
			<Param Name="Right" Type="STRING">Camera DVD Player</Param>
		</Plugin>
	</Plugin>



	<Plugin Class="VideoSourceAggregate" ID="Camera Observer">
		<Param Name="Server ID" Type="INTEGER">7</Param>
		<Param Name="Icon" Type="STRING">camera_observer</Param>
		<Plugin Class="VideoSourceAnalogVdds" Filter="Client" ID="Analog Camera 7">
			<!--
			RS170 In4
			-->
			<Include File="NTSC_GENERIC_Frame"/>
			<Param Name="Video Input Port" Type="INTEGER">3</Param>
		</Plugin>
		<Plugin Class="CmdCameraSelector">
			<Param Name="Up" Type="STRING">Camera Front</Param>
			<Param Name="Down" Type="STRING">Camera Rear Color</Param>
			<Param Name="Left" Type="STRING">Camera Left</Param>
			<Param Name="Right" Type="STRING">Camera DVD Player</Param>
		</Plugin>
		<Plugin Class="CamDveDiscrete" Filter="Client" ID="Client DVE Camera 0">
			<Param Name="DVE Input Port" Type="INTEGER">3</Param>
		</Plugin>
	</Plugin>
</Plugins>

=== grizzie17/GS8/Config/plugins/commands/MO_vdds.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Command Plugins -->
<Plugins Group=""
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../plugin.xsd">


	<Include File="vdds_common"/>
	<Include File="vcb_constants"/>
	
	<Plugin Class="CmdConstant" Group="" ID="Video Source Constants">
		<Param Name="Camera Front" Type="STRING">Camera Front</Param>
		<Param Name="Camera Left" Type="STRING">Camera Left</Param>
		<Param Name="Camera Right" Type="STRING">Camera Right</Param>
		<Param Name="Camera Rear Color" Type="STRING">Camera Rear Color</Param>
		<Param Name="Camera Rear IR" Type="STRING">Camera Rear IR</Param>
    <Param Name="Camera DVD Player" Type="STRING">Camera DVD Player</Param>
    <Param Name="Camera DCM Text" Type="STRING">Camera DCM Text</Param>
    <Param Name="Camera Observer" Type="STRING">Camera Observer</Param>
  </Plugin>

	<Plugin Class="CmdEptm" Group="" ID="Pan and Tilt control">
		<!-- -->
	</Plugin>
</Plugins>

=== grizzie17/GS8/Config/plugins/commands/workbench_NVL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Command Plugins -->
<Plugins Group=""
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../plugin.xsd">


	<Include File="workbench_common"/>


	<Plugin Class="CmdConstant" Group="" ID="Video Source Constants">
		<Param Name="Camera Front Right" Type="STRING">Camera Front Right</Param>
		<Param Name="Camera Front Left" Type="STRING">Camera Front Left</Param>
		<Param Name="Camera Front" Type="STRING">Camera Front</Param>
		<Param Name="Camera Rear IR" Type="STRING">Camera Rear IR</Param>
		<Param Name="Camera Rear Color" Type="STRING">Camera Rear Color</Param>
		<Param Name="Camera Rear Right" Type="STRING">Camera Rear Right</Param>
		<Param Name="Camera Rear Left" Type="STRING">Camera Rear Left</Param>
		<Param Name="Camera Observer" Type="STRING">Camera Observer</Param>
	</Plugin>

	<!--
	Define constant values describing user input direction pressed
	-->
	<Plugin Class="CmdConstant" Group="" ID="VCB Input Constants">
		<Param Name="UP" Type="INTEGER">0</Param>
		<Param Name="DOWN" Type="INTEGER">1</Param>
		<Param Name="LEFT" Type="INTEGER">2</Param>
		<Param Name="RIGHT" Type="INTEGER">3</Param>
	</Plugin>

	<!--
		NOTE: The Main Menu ID may be changed to suite the user. It will change the order
		of the display only. At this time, the Sub and SubSubmenu items cannot be updated in 
		this manner. Changing the SubSub Menu ID values below will not have an affect on 
		order. The ID's uniquelly identifies each possbile menu only. The only 
		requirement is that they each have a unique value. "Main Menu ID MAX" identifies
		the number of Main Menu IDs and must be left unchanged.
	-->
	<Plugin Class="CmdConstant" Group="" ID="Menu ID Constants">
		<Param Name="SubSub Menu ID None" Type="INTEGER">0</Param>
		<Param Name="SubSub Menu ID CONFIRM SHUTDOWN" Type="INTEGER">1</Param>
		<Param Name="SubSub Menu ID AGC MODE" Type="INTEGER">2</Param>
		<Param Name="SubSub Menu ID ADJUST LEVEL" Type="INTEGER">3</Param>
		<Param Name="SubSub Menu ID ADJUST GAIN" Type="INTEGER">4</Param>
		<Param Name="Main Menu ID SCREEN MODE" Type="INTEGER">0</Param>
		<Param Name="Main Menu ID CAMERA SETTINGS" Type="INTEGER">1</Param>
		<Param Name="Main Menu ID QUADRANT" Type="INTEGER">2</Param>
		<Param Name="Main Menu ID MISC" Type="INTEGER">3</Param>
		<Param Name="Main Menu ID EXIT" Type="INTEGER">4</Param>
		<Param Name="Main Menu ID MAX" Type="INTEGER">5</Param>
	</Plugin>

	<!--
	<Plugin Class="CmdWBReturnTrue" Group="" ID="Extra Commands">
		<Param Name="Send Point External" Type="INTEGER">0</Param>
	</Plugin>
	-->

	<Include File="../videosources/active"/>

</Plugins>

=== grizzie17/GS8/Config/plugins/commands/workbench_MO.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Command Plugins -->
<Plugins Group=""
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../plugin.xsd">


	<Include File="workbench_common"/>



	<Plugin Class="CmdConstant" Group="" ID="Video Source Constants">
		<Param Name="Camera Front" Type="STRING">Camera Front</Param>
		<Param Name="Camera Front.Icon" Type="STRING">Icon Camera Front-Center</Param>
		<Param Name="Camera Front-Center" Type="STRING">Camera Front-Center</Param>
		<Param Name="Camera Front-Center.Icon" Type="STRING">Icon Camera Front-Center</Param>
		<Param Name="Camera Front-Left" Type="STRING">Camera Front-Left</Param>
		<Param Name="Camera Front-Left.Icon" Type="STRING">Icon Camera Front-Left</Param>
		<Param Name="Camera Front-Right" Type="STRING">Camera Front-Right</Param>
		<Param Name="Camera Front-Right.Icon" Type="STRING">Icon Camera Front-Right</Param>
		<Param Name="Camera Rear IR" Type="STRING">Camera Rear IR</Param>
		<Param Name="Camera Rear IR.Icon" Type="STRING">Icon Camera Rear</Param>
		<Param Name="Camera Rear Color" Type="STRING">Camera Rear Color</Param>
		<Param Name="Camera Rear Color.Icon" Type="STRING">Icon Camera Rear</Param>
		<Param Name="Camera Left" Type="STRING">Camera Left</Param>
		<Param Name="Camera Left.Icon" Type="STRING">Icon Camera Left</Param>
		<Param Name="Camera Right" Type="STRING">Camera Right</Param>
		<Param Name="Camera Right.Icon" Type="STRING">Icon Camera Right</Param>
		<Param Name="Camera Observer" Type="STRING">Camera Observer</Param>
		<Param Name="Camera Observer.Icon" Type="STRING">Icon Camera Observer</Param>
		<Param Name="Camera DVD Player" Type="STRING">Camera DVD</Param>
		<Param Name="Camera DVD Player.Icon" Type="STRING">Icon Camera DVD</Param>
		<Param Name="PC Video" Type="STRING">PC Video</Param>
		<Param Name="PC Video.Icon" Type="STRING">Icon PC Video</Param>
		<Param Name="Camera DCM Text" Type="STRING">PC Video</Param>
		<Param Name="Camera DCM Text.Icon" Type="STRING">Icon PC Video</Param>
		<Param Name="Camera Aux 1" Type="STRING">Camera Aux 1</Param>
		<Param Name="Camera Aux 1.Icon" Type="STRING">Icon Camera Aux 1</Param>
		<Param Name="Camera Aux 2" Type="STRING">Camera Aux 2</Param>
		<Param Name="Camera Aux 2.Icon" Type="STRING">Icon Camera Aux 2</Param>
	</Plugin>


	<Include File="VehicleDataSample"/>



	<Plugin Class="CmdEptm" Group="" ID="Pan and Tilt control">
		<!-- -->
	</Plugin>


</Plugins>

=== grizzie17/GS8/Config/plugins/inputdevices/uk_3head_input_dev_left.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Plugin information -->
<Plugins Group=""
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../plugin.xsd">
	<Plugin Class="InputUk3HeadCtd10" ID="Touch Screen 0">
      		<Param Name="Display Port" Type="INTEGER">1</Param>
		<Param Name="Port" Type="STRING">/dev/tts/1</Param>
		<Param Name="Baud" Type="INTEGER">9600</Param>
		<Param Name="Parity" Type="STRING">None</Param>
		<Param Name="Stop Bits" Type="INTEGER">1</Param>
		<Param Name="Data Bits" Type="INTEGER">8</Param>
		<Param Name="Flow Control" Type="STRING">None</Param>

	     	<Param Name="CAN Used" Type="INTEGER">1</Param>
	     	<Param Name="CAN Port" Type="STRING">/dev/can1</Param>
	      	<Param Name="CAN Port Num" Type="INTEGER">2</Param>
	      <!--CAN Port Num is 1 based -->
	     	<Param Name="Display Port 2" Type="INTEGER">2</Param>
	     	<Param Name="Display Port 3" Type="INTEGER">3</Param>
	      	<Param Name="CAN Baud Rate" Type="INTEGER">250</Param>
	      	<Param Name="Termination" Type="INTEGER">1</Param>

	</Plugin>
</Plugins>

=== grizzie17/GS8/Config/plugins/inputdevices/input_devices_0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Plugin information -->
<Plugins Group=""
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../plugin.xsd">
	<Plugin Class="InputSerialPassThruBiDirectionalVDDS" ID="CM - EPTM">

		<Plugin Class="CommSerialPassThruBiDirectionalVDDS" ID="RS485">
			<!-- CM  - 485 serial port configuration-->
			<Param Name="Port1" Type="STRING">/dev/ttyVDDS17080</Param>
			<Param Name="Baud1" Type="INTEGER">19200</Param>
			<Param Name="Parity1" Type="STRING">None</Param>
			<Param Name="Stop Bits1" Type="INTEGER">1</Param>
			<Param Name="Data Bits1" Type="INTEGER">8</Param>
			<Param Name="Flow Control1" Type="STRING">None</Param>

			<!-- EPTM - 485 serial port configuration -->
			<Param Name="Port2" Type="STRING">/dev/ttyVDDS4850</Param>
			<Param Name="Baud2" Type="INTEGER">19200</Param>
			<Param Name="Parity2" Type="STRING">None</Param>
			<Param Name="Stop Bits2" Type="INTEGER">1</Param>
			<Param Name="Data Bits2" Type="INTEGER">8</Param>
			<Param Name="Flow Control2" Type="STRING">None</Param>
		</Plugin>
	</Plugin>


	<Plugin Class="InputGdcCfpd10" ID="GDC CFPD 10">
		<!-- Avalex touch screen input device -->
		<Plugin Class="CommSerialVDDS" ID="RS-422 1">
			<!--IDataStream plugin -->
			<Param Name="Port" Type="STRING">/dev/ttyVDDS0</Param>
			<Param Name="Baud" Type="INTEGER">9600</Param>
			<Param Name="Parity" Type="STRING">None</Param>
			<Param Name="Stop Bits" Type="INTEGER">1</Param>
			<Param Name="Data Bits" Type="INTEGER">8</Param>
			<Param Name="Flow Control" Type="STRING">None</Param>
			<Param Name="Non Blocking" Type="BOOL">false</Param>
		</Plugin>
		<Plugin Class="MsgGdcCfpd10" ID="GdcCfpd10 Msg 0">
			<!--IDataLink plugin -->
		</Plugin>
		<Plugin Class="EventGraphicsVDDS" ID="Graphic Events 0">
			<!--IGraphicsEvent plugin -->
		</Plugin>
		<Plugin Class="CmdVcb" ID="Menu Light 0">
			<!--CmdVcb plugin -->
		</Plugin>
	</Plugin>


</Plugins>

=== grizzie17/GS8/Config/plugins/drawobjs/MSWIN32.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Task Plugins -->
<Plugins Group="" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="../plugin.xsd">

	<!--<Plugin Class="CDrawWorkbench" Group="" ID="Draw">
		<Plugin Class="CDrawWinGL" Group="" ID="DrawGL" >
			<Param Name="Display Dirty Rectangle" Type="BOOLEAN">false</Param>
			<Param Name="Double Backingstore" Type="BOOLEAN">true</Param>

			<Param Name="Background Color" Type="COLOR">background</Param>
			<Plugin Class="CDrawTmxWin" Group="" ID="CDrawTmxWin">
				<Param Name="Proxy" Type="STRING">Dummy param</Param>
			</Plugin>
		</Plugin>
	</Plugin>-->

	
	<!--<Plugin Class="CDrawWorkbench" Group="" ID="Draw">
		<Plugin Class="CDrawWinGLTex" Group="" ID="DrawGL" >
			<Param Name="Display Dirty Rectangle" Type="BOOLEAN">false</Param>
			<Param Name="Double Backingstore" Type="BOOLEAN">true</Param>

			<Param Name="Background Color" Type="COLOR">background</Param>
			
			<Plugin Class="CDrawTmxWin" Group="" ID="CDrawTmxWin">
				<Param Name="Proxy" Type="STRING">Dummy param</Param>
			</Plugin>
		</Plugin>
	</Plugin>-->


	<!--<Plugin Class="CDrawWorkbench" Group="" ID="Draw">
		<Plugin Class="CDrawWinGLES" Group="" ID="DrawGL" >
			<Param Name="Display Dirty Rectangle" Type="BOOLEAN">false</Param>
			<Param Name="Double Backingstore" Type="BOOLEAN">true</Param>

			<Param Name="Background Color" Type="COLOR">background</Param>

			<Plugin Class="CDrawTmxWin" Group="" ID="CDrawTmxWin">
				<Param Name="Proxy" Type="STRING">Dummy param</Param>
			</Plugin>
		</Plugin>
	</Plugin>-->


	<!--<Plugin Class="CDrawWorkbench" Group="" ID="Draw">
		<Plugin Class="CDrawWinDD" Group="" ID="Draw" >
			<Param Name="Display Dirty Rectangle" Type="BOOLEAN">false</Param>
			<Param Name="Double Backingstore" Type="BOOLEAN">true</Param>

			<Param Name="Background Color" Type="COLOR">background</Param>
			<Plugin Class="CDrawTmxWin" Group="" ID="CDrawTmxWin">
				<Param Name="Proxy" Type="STRING">Dummy param</Param>
			</Plugin>
		</Plugin>
	</Plugin>-->
	<!--<Plugin Class="CDrawWorkbench" Group="" ID="Draw">
		<Plugin Class="CDrawWinDD" Group="" ID="Draw" >
			<Param Name="Display Dirty Rectangle" Type="BOOLEAN">false</Param>
			<Param Name="Double Backingstore" Type="BOOLEAN">false</Param>

			<Param Name="Background Color" Type="COLOR">background</Param>
			<Plugin Class="CDrawTmxWin" Group="" ID="CDrawTmxWin">
				<Param Name="Proxy" Type="STRING">Dummy param</Param>
			</Plugin>
		</Plugin>
	</Plugin>-->

	
	
	<Plugin Class="CDrawWorkbench" Group="" ID="Draw">
		<Plugin Class="CDrawWin" Group="" ID="DrawWin" >
			<Param Name="Display Dirty Rectangle" Type="BOOLEAN">false</Param>
			<Param Name="Double Backingstore" Type="BOOLEAN">true</Param>

			<Param Name="Background Color" Type="COLOR">background</Param>
			<Plugin Class="CDrawTmxWin" Group="" ID="CDrawTmxWin">
				<Param Name="Proxy" Type="STRING">Dummy param</Param>
			</Plugin>
		</Plugin>
	</Plugin>
	<!--<Plugin Class="CDrawWorkbench" Group="" ID="Draw">
		<Plugin Class="CDrawWin" Group="" ID="Draw" >
			<Param Name="Display Dirty Rectangle" Type="BOOLEAN">false</Param>
			<Param Name="Double Backingstore" Type="BOOLEAN">false</Param>

			<Param Name="Background Color" Type="COLOR">background</Param>
			<Plugin Class="CDrawTmxWin" Group="" ID="CDrawTmxWin">
				<Param Name="Proxy" Type="STRING">Dummy param</Param>
			</Plugin>
		</Plugin>
	</Plugin>-->


</Plugins>
